# Generated by Django 4.2.10 on 2024-02-07 11:35

from django.db import migrations, models
import django.utils.timezone
import backend.apps.uploader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='form-data', upload_to=backend.apps.uploader.models.content_file_name, verbose_name='文件对象')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('belong_to', models.CharField(help_text='文件归属', max_length=100, verbose_name='文件归属')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
            },
        ),
    ]
