# Generated by Django 4.2.10 on 2024-06-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileobject',
            name='file_info',
            field=models.JSONField(blank=True, help_text='文件信息', null=True, verbose_name='文件信息'),
        ),
    ]
