# Generated by Django 4.2.16 on 2024-09-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRequestLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(db_index=True, default='', max_length=50, verbose_name='请求内容')),
                ('execution_time', models.CharField(max_length=50, verbose_name='耗时')),
                ('timestamp', models.DateTimeField(verbose_name='请求时间')),
                ('ip_address', models.GenericIPAddressField(verbose_name='客户端ip')),
                ('request_method', models.CharField(max_length=20, verbose_name='请求方式')),
                ('full_path', models.TextField(verbose_name='请求地址')),
                ('query_params', models.TextField(verbose_name='请求参数')),
                ('data', models.TextField(verbose_name='请求体')),
                ('res_code', models.IntegerField(blank=True, null=True, verbose_name='响应code')),
                ('res_data', models.CharField(blank=True, max_length=500, null=True, verbose_name='返回数据')),
            ],
            options={
                'verbose_name': '请求操作日志',
                'verbose_name_plural': '请求操作日志',
            },
        ),
    ]
