# Generated by Django 4.2.20 on 2025-09-16 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_orgtree_is_deleted'),
        ('custom_reqlogs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequestlogs',
            name='app_key',
            field=models.CharField(blank=True, db_index=True, help_text='应用菜单Key', max_length=100, null=True, verbose_name='应用菜单Key'),
        ),
        migrations.AddField(
            model_name='customrequestlogs',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.orgtree', verbose_name='组织'),
        ),
        migrations.AlterField(
            model_name='customrequestlogs',
            name='res_data',
            field=models.TextField(blank=True, help_text='返回数据', null=True, verbose_name='返回数据'),
        ),
    ]
