# Generated by Django 4.2.20 on 2025-09-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_orgtree_is_deleted'),
        ('custom_reqlogs', '0003_customrequestlogs_app_key_customrequestlogs_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequestlogs',
            name='project',
            field=models.ForeignKey(blank=True, help_text='项目', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='项目'),
        ),
    ]
