# Generated by Django 4.2.20 on 2025-04-01 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0036_alter_categorymodemapping_device_type'),
        ('projects', '0023_alter_projects_title'),
        ('device_models', '0032_switchmonitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchMonitorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='节点名称', max_length=60, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('group', '分组'), ('device', '设备')], db_index=True, default='group', help_text='节点类型', max_length=10, verbose_name='节点类型')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('device', models.ForeignKey(blank=True, help_text='关联设备', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.device', verbose_name='关联设备')),
                ('org', models.ForeignKey(blank=True, help_text='所属组织', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_switch_monitors', to='projects.orgtree', verbose_name='所属组织')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='父节点', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='switch_monitor.switchmonitornode', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '开关监控-树结构',
                'verbose_name_plural': '开关监控-树结构',
            },
        ),
        migrations.CreateModel(
            name='SwitchDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('node', models.OneToOneField(blank=True, help_text='分组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_switch_monitor', to='switch_monitor.switchmonitornode', verbose_name='分组')),
                ('switch_monitor', models.ForeignKey(help_text='开关监控模型设备', on_delete=django.db.models.deletion.CASCADE, related_name='switch_devices', to='device_models.switchmonitor', verbose_name='开关监控模型设备')),
            ],
            options={
                'verbose_name': '开关监控应用设备',
                'verbose_name_plural': '开关监控应用设备',
            },
        ),
    ]
