# Generated by Django 4.2.20 on 2025-04-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0033_environmentmonitor'),
        ('switch_monitor', '0002_alter_switchmonitornode_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchmonitornode',
            name='switch_monitor',
            field=models.ForeignKey(blank=True, help_text='开关监控模型设备', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch_monitor_nodes', to='device_models.switchmonitor', verbose_name='开关监控模型设备'),
        ),
    ]
