# Generated by Django 4.2.20 on 2025-06-24 17:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0023_alter_projects_title'),
        ('device_models', '0033_environmentmonitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyWasteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分组名称', max_length=100, verbose_name='分组名称')),
                ('ordering', models.PositiveBigIntegerField(db_index=True, default=0, help_text='排序', verbose_name='排序')),
                ('working_time_cfg', models.JSONField(blank=True, help_text='工作时间信息', null=True, verbose_name='工作时间信息')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('org', models.ForeignKey(help_text='组织', on_delete=django.db.models.deletion.CASCADE, related_name='org_ew_groups', to='projects.orgtree', verbose_name='组织')),
            ],
            options={
                'verbose_name': ' 能耗浪费分组表',
                'verbose_name_plural': ' 能耗浪费分组表',
                'unique_together': {('org', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EnergyWasteDailyCfg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_time_cfg', models.JSONField(help_text='工作时间信息', verbose_name='工作时间信息')),
                ('devices', models.JSONField(help_text='统计设备列表', verbose_name='统计设备列表')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('group', models.ForeignKey(help_text='所属分组', on_delete=django.db.models.deletion.CASCADE, related_name='group_ew_cfgs', to='energy_waste_statistics.energywastegroup', verbose_name='所属分组')),
            ],
            options={
                'verbose_name': '分组能耗浪费统计每日配置表',
                'verbose_name_plural': '分组能耗浪费统计每日配置表',
            },
        ),
        migrations.CreateModel(
            name='EnergyWasteDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveBigIntegerField(db_index=True, default=0, help_text='分组排序', verbose_name='分组排序')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('electric_meter', models.ForeignKey(help_text='电表', on_delete=django.db.models.deletion.CASCADE, to='device_models.electricmeter', verbose_name='电表')),
                ('group', models.ForeignKey(blank=True, help_text='所属分组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_ew_devices', to='energy_waste_statistics.energywastegroup', verbose_name='所属分组')),
                ('org', models.ForeignKey(help_text='组织', on_delete=django.db.models.deletion.CASCADE, related_name='org_ew_devices', to='projects.orgtree', verbose_name='组织')),
            ],
            options={
                'verbose_name': '能耗浪费设备',
                'verbose_name_plural': '能耗浪费设备',
                'unique_together': {('org', 'electric_meter')},
            },
        ),
        migrations.CreateModel(
            name='EnergyWasteDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb', models.FloatField(blank=True, help_text='浪费电量', null=True, verbose_name='浪费电量')),
                ('statistic_date', models.DateField(db_index=True, help_text='统计日期', verbose_name='统计日期')),
                ('ew_daily_cfg', models.ForeignKey(blank=True, help_text='当日统计配置', null=True, on_delete=django.db.models.deletion.SET_NULL, to='energy_waste_statistics.energywastedailycfg', verbose_name='当日统计配置')),
                ('group', models.ForeignKey(help_text='所属分组', on_delete=django.db.models.deletion.CASCADE, related_name='group_ew_datas', to='energy_waste_statistics.energywastegroup', verbose_name='所属分组')),
            ],
            options={
                'verbose_name': '能耗浪费统计数据',
                'verbose_name_plural': '能耗浪费统计数据',
                'unique_together': {('group', 'statistic_date')},
            },
        ),
    ]
