# Generated by Django 4.2.20 on 2025-07-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_waste_statistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energywastedailycfg',
            name='devices',
        ),
        migrations.AddField(
            model_name='energywastedailydata',
            name='devices_data',
            field=models.JSONField(blank=True, help_text='设备统计明细', null=True, verbose_name='设备统计明细'),
        ),
    ]
