# Generated by Django 4.2.16 on 2024-09-12 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgTree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='机构名称', max_length=50, verbose_name='机构名称')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': '组织机构',
                'verbose_name_plural': '组织机构',
            },
        ),
        migrations.CreateModel(
            name='ProjectMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(10, '拥有者'), (20, '管理员'), (30, '普通用户')], default=10, help_text='权限级别', verbose_name='权限级别')),
                ('desc', models.TextField(blank=True, help_text='描述', null=True, verbose_name='描述')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目成员明细',
                'verbose_name_plural': '项目成员明细',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='尚未命名', help_text='项目名称', max_length=100, verbose_name='项目名称')),
                ('desc', models.TextField(blank=True, help_text='项目描述', null=True, verbose_name='项目描述')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='位置')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除', verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='名称', max_length=50, verbose_name='名称')),
                ('code', models.CharField(blank=True, help_text='编码', max_length=20, null=True, unique=True, verbose_name='编码')),
                ('description', models.TextField(blank=True, help_text='站点描述', null=True, verbose_name='站点描述')),
                ('longitude', models.FloatField(blank=True, help_text='经度', null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, help_text='纬度', null=True, verbose_name='纬度')),
                ('location', models.CharField(blank=True, help_text='位置', max_length=100, null=True, verbose_name='位置')),
                ('mobile', models.CharField(blank=True, help_text='联系方式', max_length=20, null=True, verbose_name='联系方式')),
                ('manager', models.CharField(blank=True, help_text='负责人', max_length=20, null=True, verbose_name='负责人')),
                ('image', models.TextField(blank=True, help_text='封面图片', null=True, verbose_name='封面图片')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('running_date', models.DateField(blank=True, help_text='投运日期', null=True, verbose_name='投运日期')),
                ('city', models.ForeignKey(blank=True, help_text='所在城市', null=True, on_delete=django.db.models.deletion.SET_NULL, to='areas.area', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
            },
        ),
    ]
