# Generated by Django 4.2.16 on 2024-09-12 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_perm', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='station',
            name='menus',
            field=models.ManyToManyField(help_text='站点应用菜单', related_name='station_menus', to='custom_perm.appmenus', verbose_name='站点应用菜单'),
        ),
        migrations.AddField(
            model_name='station',
            name='org',
            field=models.ForeignKey(help_text='所属机构', on_delete=django.db.models.deletion.CASCADE, related_name='org_stations', to='projects.orgtree', verbose_name='所属机构'),
        ),
        migrations.AddField(
            model_name='station',
            name='project',
            field=models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.CASCADE, related_name='project_stations', to='projects.projects', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projects',
            name='creator',
            field=models.ForeignKey(help_text='创建人', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='projects',
            name='menus',
            field=models.ManyToManyField(help_text='项目应用菜单', related_name='project_menus', to='custom_perm.appmenus', verbose_name='项目应用菜单'),
        ),
        migrations.AddField(
            model_name='projectmembers',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='项目成员记录创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='项目成员记录创建人'),
        ),
        migrations.AddField(
            model_name='projectmembers',
            name='org',
            field=models.ForeignKey(help_text='所属机构', on_delete=django.db.models.deletion.CASCADE, related_name='org_menus', to='projects.orgtree', verbose_name='所属机构'),
        ),
        migrations.AddField(
            model_name='projectmembers',
            name='project',
            field=models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='projects.projects', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projectmembers',
            name='user',
            field=models.ForeignKey(help_text='项目成员', on_delete=django.db.models.deletion.CASCADE, related_name='user_members', to=settings.AUTH_USER_MODEL, verbose_name='项目成员'),
        ),
        migrations.AddField(
            model_name='orgtree',
            name='menus',
            field=models.ManyToManyField(help_text='机构应用菜单', related_name='org_menus', to='custom_perm.appmenus', verbose_name='机构应用菜单'),
        ),
        migrations.AddField(
            model_name='orgtree',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='上级机构', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.orgtree', verbose_name='上级机构'),
        ),
        migrations.AddField(
            model_name='orgtree',
            name='project',
            field=models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.CASCADE, related_name='project_orgs', to='projects.projects', verbose_name='项目'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmembers',
            unique_together={('project', 'user')},
        ),
    ]
