# Generated by Django 4.2.16 on 2024-09-13 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='orgtree',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='orgtree',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='项目成员记录创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='项目成员记录创建人'),
        ),
        migrations.AddField(
            model_name='orgtree',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='orgtree',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
