# Generated by Django 4.2.16 on 2024-09-13 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_station_is_deleted_orgtree_created_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='location',
        ),
        migrations.AlterField(
            model_name='projectmembers',
            name='org',
            field=models.ForeignKey(blank=True, help_text='所属机构', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_menus', to='projects.orgtree', verbose_name='所属机构'),
        ),
    ]
