# Generated by Django 4.2.16 on 2024-10-31 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_remove_projects_location_alter_projectmembers_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgTreeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.orgtree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '机构成员',
                'verbose_name_plural': '机构成员',
            },
        ),
        migrations.AddField(
            model_name='orgtree',
            name='users',
            field=models.ManyToManyField(help_text='机构成员', related_name='org_users', through='projects.OrgTreeUser', to=settings.AUTH_USER_MODEL, verbose_name='机构成员'),
        ),
    ]
