# Generated by Django 4.2.16 on 2024-11-07 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_orgtreeuser_orgtree_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmembers',
            name='level',
        ),
        migrations.AlterField(
            model_name='orgtree',
            name='users',
            field=models.ManyToManyField(help_text='机构成员', related_name='user_orgs', through='projects.OrgTreeUser', to=settings.AUTH_USER_MODEL, verbose_name='机构成员'),
        ),
        migrations.AlterField(
            model_name='projectmembers',
            name='org',
            field=models.ForeignKey(blank=True, help_text='所属机构', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_members', to='projects.orgtree', verbose_name='所属机构'),
        ),
    ]
