# Generated by Django 4.2.16 on 2024-11-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_servers', '0006_remove_aircondgroup_station_and_more'),
        ('equipments', '0008_remove_device_org_remove_device_station'),
        ('projects', '0006_remove_projectmembers_level_alter_orgtree_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='city',
        ),
        migrations.RemoveField(
            model_name='station',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='station',
            name='menus',
        ),
        migrations.RemoveField(
            model_name='station',
            name='org',
        ),
        migrations.RemoveField(
            model_name='station',
            name='project',
        ),
        migrations.RemoveField(
            model_name='orgtree',
            name='menus',
        ),
        migrations.RemoveField(
            model_name='orgtree',
            name='users',
        ),
        migrations.RemoveField(
            model_name='projectmembers',
            name='org',
        ),
        migrations.AddField(
            model_name='projectmembers',
            name='orgs',
            field=models.ManyToManyField(help_text='所属机构', related_name='org_members', to='projects.orgtree', verbose_name='所属机构'),
        ),
        migrations.DeleteModel(
            name='OrgTreeUser',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
