# Generated by Django 4.2.16 on 2024-11-29 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_perm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_remove_station_city_remove_station_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsAppMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='尚未命名', help_text='项目名称', max_length=100, verbose_name='项目名称')),
                ('desc', models.TextField(blank=True, help_text='项目描述', null=True, verbose_name='项目描述')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('app_menu', models.ForeignKey(help_text='应用菜单', on_delete=django.db.models.deletion.CASCADE, related_name='app_menu_projects', to='custom_perm.appmenus', verbose_name='应用菜单')),
                ('creator', models.ForeignKey(blank=True, help_text='项目成员记录创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='项目成员记录创建人')),
                ('project', models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.CASCADE, related_name='project_app_menus', to='projects.projects', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目应用',
                'verbose_name_plural': '项目应用',
            },
        ),
    ]
