# Generated by Django 4.2.16 on 2024-11-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectsappmenus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='menus',
        ),
        migrations.RemoveField(
            model_name='projectsappmenus',
            name='app_menu',
        ),
        migrations.AddField(
            model_name='projectsappmenus',
            name='app_key',
            field=models.CharField(blank=True, help_text='应用菜单Key', max_length=100, null=True, verbose_name='应用菜单Key'),
        ),
        migrations.AlterField(
            model_name='projectsappmenus',
            name='name',
            field=models.CharField(default='尚未命名', help_text='应用名称', max_length=100, verbose_name='应用名称'),
        ),
    ]
