# Generated by Django 4.2.16 on 2024-11-29 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_projects_menus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsappmenus',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
        ),
    ]
