# Generated by Django 4.2.16 on 2024-12-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectsappmenus_ordering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembers',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
