# Generated by Django 4.2.16 on 2024-12-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectmembers_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='alarm_types',
            field=models.JSONField(blank=True, help_text='告警类型配置', null=True, verbose_name='告警类型配置'),
        ),
    ]
