# Generated by Django 4.2.16 on 2024-12-30 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_projects_alarm_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsappmenus',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='项目应用建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='项目应用创建人'),
        ),
        migrations.AlterField(
            model_name='projectsappmenus',
            name='desc',
            field=models.TextField(blank=True, help_text='项目应用描述', null=True, verbose_name='项目应用描述'),
        ),
        migrations.CreateModel(
            name='OrgAppMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('ordering', models.IntegerField(default=0, verbose_name='排序')),
                ('creator', models.ForeignKey(blank=True, help_text='组织应用创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='组织应用创建人')),
                ('org', models.ForeignKey(help_text='所属组织', on_delete=django.db.models.deletion.CASCADE, related_name='org_app_menus', to='projects.orgtree', verbose_name='所属组织')),
                ('project_app', models.ForeignKey(help_text='项目应用', on_delete=django.db.models.deletion.CASCADE, related_name='project_app_orgs', to='projects.projectsappmenus', verbose_name='项目应用')),
            ],
            options={
                'verbose_name': '组织应用',
                'verbose_name_plural': '组织应用',
                'unique_together': {('org', 'project_app')},
            },
        ),
    ]
