# Generated by Django 4.2.16 on 2025-01-07 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0024_alter_categorymodemapping_device_type'),
        ('projects', '0013_alter_projectsappmenus_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='ezt_project',
            field=models.ForeignKey(blank=True, help_text='Ezt项目', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.eztprojects', verbose_name='Ezt项目'),
        ),
    ]
