# Generated by Django 4.2.16 on 2025-01-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projects_ezt_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='remark',
            field=models.TextField(blank=True, help_text='项目备注', null=True, verbose_name='项目备注'),
        ),
    ]
