# Generated by Django 4.2.16 on 2025-01-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projects_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(default='EztCloud数据应用系统', help_text='项目标题', max_length=100, verbose_name='项目标题'),
        ),
    ]
