# Generated by Django 4.2.16 on 2025-01-10 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0016_projects_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='角色名称', max_length=150, verbose_name='角色名称')),
                ('desc', models.TextField(blank=True, help_text='角色描述', null=True, verbose_name='角色描述')),
                ('ordering', models.IntegerField(default=0, verbose_name='排序')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('permissions', models.ManyToManyField(blank=True, help_text='角色权限', to='auth.permission', verbose_name='角色权限')),
                ('project', models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.CASCADE, related_name='project_groups', to='projects.projects', verbose_name='项目')),
                ('users', models.ManyToManyField(help_text='角色成员', related_name='user_project_groups', to=settings.AUTH_USER_MODEL, verbose_name='角色成员')),
            ],
            options={
                'verbose_name': '项目角色',
                'verbose_name_plural': '项目角色',
                'unique_together': {('project', 'name')},
            },
        ),
    ]
