# Generated by Django 4.2.16 on 2025-01-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0017_projectgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='角色权限', related_name='perm_project_groups', to='auth.permission', verbose_name='角色权限'),
        ),
    ]
