# Generated by Django 4.2.16 on 2025-01-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_projectgroup_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgtree',
            options={'permissions': (('org_device_manage', '组织设备管理'),), 'verbose_name': '组织机构', 'verbose_name_plural': '组织机构'},
        ),
    ]
