# Generated by Django 4.2.16 on 2025-02-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_orgtree_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgappmenus',
            name='desc',
            field=models.TextField(blank=True, help_text='项目应用描述', null=True, verbose_name='项目应用描述'),
        ),
        migrations.AddField(
            model_name='orgappmenus',
            name='name',
            field=models.CharField(default='尚未命名', help_text='应用名称', max_length=100, verbose_name='应用名称'),
        ),
        migrations.AddField(
            model_name='orgtree',
            name='app_default_cfg',
            field=models.JSONField(blank=True, help_text='组织应用默认配置', null=True, verbose_name='组织应用默认配置'),
        ),
    ]
