# Generated by Django 4.2.16 on 2025-02-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_orgappmenus_desc_orgappmenus_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgtree',
            options={'permissions': (('org_device_manage', '组织设备管理'), ('view_org_overview', '查看组织概览'), ('change_org_overview', '操作组织概览')), 'verbose_name': '组织机构', 'verbose_name_plural': '组织机构'},
        ),
    ]
