# Generated by Django 4.2.19 on 2025-02-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('el_branch', '0004_branchtreenode_device'),
        ('projects', '0021_alter_orgtree_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgtree',
            name='el_branch_node',
            field=models.ForeignKey(blank=True, help_text='配电回路默认节点', null=True, on_delete=django.db.models.deletion.SET_NULL, to='el_branch.branchtreenode', verbose_name='配电回路默认节点'),
        ),
    ]
