# Generated by Django 4.2.19 on 2025-03-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_orgtree_el_branch_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(default='EZtCloud数据应用系统', help_text='项目标题', max_length=100, verbose_name='项目标题'),
        ),
    ]
