# Generated by Django 4.2.20 on 2025-09-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_projects_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgtree',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除'),
        ),
    ]
