# Generated by Django 4.2.20 on 2025-11-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_orgtree_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgtree',
            options={'permissions': (('org_device_manage', '组织设备管理'), ('view_org_overview', '查看组织概览'), ('change_org_overview', '操作组织概览'), ('add_org_user', '组织成员')), 'verbose_name': '组织机构', 'verbose_name_plural': '组织机构'},
        ),
    ]
