# Generated by Django 4.2.20 on 2025-11-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_alter_orgtree_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='ordering',
            field=models.IntegerField(default=0, help_text='对自己创建的项目排序', verbose_name='项目排序'),
        ),
    ]
