# Generated by Django 4.2.20 on 2025-12-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_projects_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'permissions': (('view_project_cfg', '查看控制台'), ('view_project_app', '查看工作台')), 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
    ]
