# Generated by Django 4.2.20 on 2025-04-02 18:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device_models', '0033_environmentmonitor'),
        ('projects', '0023_alter_projects_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='名称', max_length=100, verbose_name='名称')),
                ('image', models.TextField(blank=True, help_text='分布图', null=True, verbose_name='分布图')),
                ('org', models.ForeignKey(help_text='所属组织', on_delete=django.db.models.deletion.CASCADE, related_name='org_env_distributions', to='projects.orgtree', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '环境系统-分布图',
                'verbose_name_plural': '环境系统-分布图',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.CharField(help_text='x坐标', verbose_name='x坐标')),
                ('y_coordinate', models.CharField(help_text='y坐标', verbose_name='y坐标')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('distribution_map', models.ForeignKey(help_text='分布图', on_delete=django.db.models.deletion.CASCADE, related_name='dmap_env_devices', to='environment_monitor.envdistribution', verbose_name='分布图')),
                ('environment_monitor', models.ForeignKey(help_text='环境系统设备', on_delete=django.db.models.deletion.CASCADE, related_name='environment_devices', to='device_models.environmentmonitor', verbose_name='环境系统设备')),
            ],
            options={
                'verbose_name': '环境系统设备',
                'verbose_name_plural': '环境系统设备',
            },
        ),
    ]
