# Generated by Django 4.2.20 on 2025-04-03 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0037_alter_categorymodemapping_device_type'),
        ('projects', '0023_alter_projects_title'),
        ('device_models', '0033_environmentmonitor'),
        ('environment_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmentdevice',
            options={'verbose_name': '开关监控应用设备', 'verbose_name_plural': '开关监控应用设备'},
        ),
        migrations.RemoveField(
            model_name='environmentdevice',
            name='distribution_map',
        ),
        migrations.RemoveField(
            model_name='environmentdevice',
            name='x_coordinate',
        ),
        migrations.RemoveField(
            model_name='environmentdevice',
            name='y_coordinate',
        ),
        migrations.CreateModel(
            name='EnvironmentMonitorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='节点名称', max_length=60, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('group', '分组'), ('device', '设备')], db_index=True, default='group', help_text='节点类型', max_length=10, verbose_name='节点类型')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('device', models.ForeignKey(blank=True, help_text='关联设备', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.device', verbose_name='关联设备')),
                ('environment_monitor', models.ForeignKey(blank=True, help_text='环境系统设备', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environment_monitor_nodes', to='device_models.environmentmonitor', verbose_name='环境系统设备')),
                ('org', models.ForeignKey(blank=True, help_text='所属组织', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.orgtree', verbose_name='所属组织')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='父节点', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='environment_monitor.environmentmonitornode', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '开关监控-树结构',
                'verbose_name_plural': '开关监控-树结构',
            },
        ),
        migrations.CreateModel(
            name='EnvDistributionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('x_coordinate', models.CharField(help_text='x坐标', verbose_name='x坐标')),
                ('y_coordinate', models.CharField(help_text='y坐标', verbose_name='y坐标')),
                ('distribution_map', models.ForeignKey(help_text='分布图', on_delete=django.db.models.deletion.CASCADE, related_name='dmap_env_devices', to='environment_monitor.envdistribution', verbose_name='分布图')),
            ],
            options={
                'verbose_name': '环境系统设备',
                'verbose_name_plural': '环境系统设备',
            },
        ),
        migrations.AddField(
            model_name='environmentdevice',
            name='node',
            field=models.OneToOneField(blank=True, help_text='分组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_environment_device', to='environment_monitor.environmentmonitornode', verbose_name='分组'),
        ),
    ]
