# Generated by Django 4.2.20 on 2025-04-03 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment_monitor', '0002_alter_environmentdevice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmentdevice',
            options={'verbose_name': '环境系统应用设备', 'verbose_name_plural': '环境系统应用设备'},
        ),
        migrations.AlterModelOptions(
            name='environmentmonitornode',
            options={'verbose_name': '环境系统-树结构', 'verbose_name_plural': '环境系统-树结构'},
        ),
        migrations.AddField(
            model_name='envdistributiondevice',
            name='env_device',
            field=models.ForeignKey(blank=True, help_text='环境系统应用设备', null=True, on_delete=django.db.models.deletion.CASCADE, to='environment_monitor.environmentdevice', verbose_name='环境系统应用设备'),
        ),
    ]
