# Generated by Django 4.2.20 on 2025-04-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_monitor', '0003_alter_environmentdevice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envdistribution',
            name='dmap_env_devices',
            field=models.JSONField(blank=True, help_text='分布图设备', null=True, verbose_name='分布图设备'),
        ),
        migrations.DeleteModel(
            name='EnvDistributionDevice',
        ),
    ]
