# Generated by Django 4.2.20 on 2025-04-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_monitor', '0004_envdistribution_dmap_env_devices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentmonitornode',
            name='name',
            field=models.CharField(blank=True, help_text='节点名称', max_length=60, null=True, verbose_name='节点名称'),
        ),
    ]
