# Generated by Django 4.2.20 on 2025-06-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_monitor', '0005_alter_environmentmonitornode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='envdistribution',
            name='is_polling',
            field=models.BooleanField(default=False, help_text='是否开启设备轮训', verbose_name='是否开启设备轮训'),
        ),
    ]
