# Generated by Django 4.2.20 on 2025-09-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_monitor', '0006_envdistribution_is_polling'),
    ]

    operations = [
        migrations.AddField(
            model_name='envdistribution',
            name='alternative_images',
            field=models.JSONField(blank=True, help_text='分布图images', null=True, verbose_name='分布图images'),
        ),
    ]
