# Generated by Django 4.2.16 on 2024-09-12 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEZtProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '站点认证项目',
                'verbose_name_plural': '站点认证项目',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('air_cond', '空调'), ('personnel_sensor', '人体存在感应传感器'), ('space_tight_sensor', '门窗传感器')], help_text='MCP设备类别', max_length=30, verbose_name='MCP设备类别')),
                ('com_gateway', models.CharField(blank=True, help_text='网关唯一标识', max_length=100, null=True, verbose_name='网关唯一标识')),
                ('username', models.CharField(help_text='设别唯一标识', max_length=100, unique=True, verbose_name='设别唯一标识')),
                ('name', models.CharField(help_text='设备组名称', max_length=100, verbose_name='设备组名称')),
                ('desc', models.TextField(blank=True, help_text='设备分组描述信息', null=True, verbose_name='设备分组描述信息')),
                ('addr', models.CharField(blank=True, help_text='子设备标识符', max_length=50, null=True, verbose_name='子设备标识符')),
                ('is_online', models.BooleanField(default=False, help_text='是否在线', verbose_name='是否在线')),
                ('timestamp', models.DateTimeField(blank=True, help_text='数据更新时间', null=True, verbose_name='数据更新时间')),
                ('last_offline_time', models.DateTimeField(blank=True, help_text='最后离线时间', null=True, verbose_name='最后离线时间')),
                ('ordering', models.IntegerField(db_index=True, default=0, help_text='排序', verbose_name='排序')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(blank=True, help_text='EZt设备类型ID', max_length=50, null=True, verbose_name='EZt设备类型ID')),
                ('category_name', models.CharField(blank=True, help_text='EZt设备类型名称', max_length=30, null=True, verbose_name='EZt设备类型名称')),
                ('device_type', models.CharField(choices=[('air_cond', '空调'), ('personnel_sensor', '人体存在感应传感器'), ('space_tight_sensor', '门窗传感器')], help_text='MCP设备类别', max_length=30, verbose_name='MCP设备类别')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '设备类型映射表',
                'verbose_name_plural': '设备类型映射表',
            },
        ),
        migrations.CreateModel(
            name='DeviceGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='设备组名称', max_length=100, verbose_name='设备组名称')),
                ('desc', models.TextField(blank=True, help_text='设备分组描述信息', null=True, verbose_name='设备分组描述信息')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备组',
                'verbose_name_plural': '设备组',
            },
        ),
        migrations.CreateModel(
            name='EZtProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='尚未命名', help_text='项目名称', max_length=100, verbose_name='项目名称')),
                ('desc', models.TextField(blank=True, help_text='项目描述', null=True, verbose_name='项目描述')),
                ('project_key', models.CharField(help_text='Ezt项目project_key 通常以"PR_"开头，如"PR_xxxxxxxxxx', max_length=30, unique=True, verbose_name=' Ezt项目project_key')),
                ('project_secret', models.CharField(blank=True, help_text='项目连接秘钥', max_length=100, null=True, verbose_name='ProjectSecret')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
    ]
