# Generated by Django 4.2.16 on 2024-09-12 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='creator',
            field=models.ForeignKey(help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='ezt_project',
            field=models.ForeignKey(help_text='EZt项目', on_delete=django.db.models.deletion.CASCADE, to='equipments.eztprojects', verbose_name='EZt项目'),
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='project',
            field=models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.CASCADE, related_name='device_category', to='projects.projects', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.PROTECT, related_name='category_devices', to='equipments.devicecategory', verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_group',
            field=models.ForeignKey(blank=True, help_text='所属设备分组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_devices', to='equipments.devicegroups', verbose_name='所属设备分组'),
        ),
        migrations.AddField(
            model_name='device',
            name='station',
            field=models.ForeignKey(help_text='加油站站点', on_delete=django.db.models.deletion.CASCADE, related_name='station_devices', to='projects.station', verbose_name='加油站站点'),
        ),
        migrations.AddField(
            model_name='autheztprojects',
            name='creator',
            field=models.ForeignKey(help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='autheztprojects',
            name='ezt_project',
            field=models.ForeignKey(help_text='Ezt项目', on_delete=django.db.models.deletion.CASCADE, to='equipments.eztprojects', verbose_name='Ezt项目'),
        ),
        migrations.AddField(
            model_name='autheztprojects',
            name='project',
            field=models.ForeignKey(help_text='Mcq项目', on_delete=django.db.models.deletion.CASCADE, related_name='ezt_projects', to='projects.projects', verbose_name='Mcq项目'),
        ),
    ]
