# Generated by Django 4.2.16 on 2024-09-13 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_station_is_deleted_orgtree_created_time_and_more'),
        ('equipments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='org',
            field=models.ForeignKey(blank=True, help_text='机构', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_devices', to='projects.orgtree', verbose_name='机构'),
        ),
        migrations.AddField(
            model_name='device',
            name='project',
            field=models.ForeignKey(blank=True, help_text='项目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_devices', to='projects.projects', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='device',
            name='station',
            field=models.ForeignKey(blank=True, help_text='加油站站点', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_devices', to='projects.station', verbose_name='加油站站点'),
        ),
    ]
