# Generated by Django 4.2.16 on 2024-09-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_device_org_device_project_alter_device_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eztprojects',
            name='project_secret',
        ),
        migrations.AlterField(
            model_name='device',
            name='desc',
            field=models.TextField(blank=True, help_text='设备描述信息', null=True, verbose_name='设备描述信息'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='设备名称', max_length=100, verbose_name='设备名称'),
        ),
    ]
