# Generated by Django 4.2.16 on 2024-10-09 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0005_remove_eztprojects_project_secret_alter_device_desc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicecategory',
            options={'verbose_name': '设备类型表', 'verbose_name_plural': '设备类型表'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='devicecategory',
            name='device_type',
        ),
        migrations.AddField(
            model_name='autheztprojects',
            name='remark',
            field=models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='desc',
            field=models.TextField(blank=True, help_text='设备类型描述', null=True, verbose_name='设备类型描述'),
        ),
        migrations.CreateModel(
            name='CategoryModeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('air_cond', '空调'), ('personnel_sensor', '人体存在感应传感器'), ('space_tight_sensor', '门窗传感器')], help_text='MCP设备模型', max_length=30, verbose_name='MCP设备模型')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.PROTECT, related_name='device_types', to='equipments.devicecategory', verbose_name='设备类型')),
                ('creator', models.ForeignKey(help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '设备类型关联模型映射表',
                'verbose_name_plural': '设备类型关联模型映射表',
            },
        ),
    ]
