# Generated by Django 4.2.16 on 2024-10-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_alter_devicecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='node_type',
            field=models.CharField(blank=True, choices=[('DD', '直连设备'), ('CG', '网关'), ('SD', '子设备')], help_text='设备接入类型', max_length=20, null=True, verbose_name='设备接入类型'),
        ),
    ]
