# Generated by Django 4.2.16 on 2024-11-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_devicecategory_node_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='org',
        ),
        migrations.RemoveField(
            model_name='device',
            name='station',
        ),
    ]
