# Generated by Django 4.2.16 on 2024-11-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_remove_device_org_remove_device_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除'),
        ),
    ]
