# Generated by Django 4.2.16 on 2024-11-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_device_is_deleted_devicecategory_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='devicecategory',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='device',
            name='is_invalid',
            field=models.BooleanField(default=False, help_text='是否已失效', verbose_name='是否已失效'),
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='is_invalid',
            field=models.BooleanField(default=False, help_text='是否已失效', verbose_name='是否已失效'),
        ),
    ]
