# Generated by Django 4.2.16 on 2024-11-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_remove_device_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='online_delay_time',
            field=models.IntegerField(default=300, help_text='设备在线延迟时间', verbose_name='设备在线延迟时间'),
        ),
    ]
