# Generated by Django 4.2.16 on 2024-11-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0011_devicecategory_online_delay_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, help_text='数据更新时间', null=True, verbose_name='数据更新时间'),
        ),
    ]
