# Generated by Django 4.2.16 on 2024-12-06 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0012_alter_device_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodemapping',
            name='category',
            field=models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.CASCADE, related_name='device_types', to='equipments.devicecategory', verbose_name='设备类型'),
        ),
    ]
