# Generated by Django 4.2.16 on 2024-12-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0013_alter_categorymodemapping_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodemapping',
            name='device_type',
            field=models.CharField(choices=[('air_cond', '空调'), ('personnel_sensor', '人体存在感应传感器'), ('space_tight_sensor', '门窗传感器'), ('electric_meter', '电表')], help_text='MCP设备模型', max_length=30, verbose_name='MCP设备模型'),
        ),
    ]
