# Generated by Django 4.2.16 on 2024-12-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectmembers_ordering'),
        ('equipments', '0018_alter_categorymodemapping_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='orgs',
            field=models.ManyToManyField(help_text='组织', related_name='org_devices', to='projects.orgtree', verbose_name='组织'),
        ),
    ]
