# Generated by Django 4.2.16 on 2025-01-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0022_alter_categorymodemapping_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, help_text='设备安裝位置', max_length=100, null=True, verbose_name='设备安裝位置'),
        ),
    ]
