# Generated by Django 4.2.16 on 2025-01-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0024_alter_categorymodemapping_device_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthEZtProjects',
        ),
    ]
