# Generated by Django 4.2.16 on 2025-01-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0025_delete_autheztprojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(help_text='设备类型', on_delete=django.db.models.deletion.CASCADE, related_name='category_devices', to='equipments.devicecategory', verbose_name='设备类型'),
        ),
    ]
