# Generated by Django 4.2.16 on 2025-01-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_projects_title'),
        ('equipments', '0026_alter_device_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegroups',
            name='project',
            field=models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.CASCADE, related_name='project_device_groups', to='projects.projects', verbose_name='项目'),
        ),
    ]
