# Generated by Django 4.2.16 on 2025-01-16 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0019_alter_orgtree_options'),
        ('equipments', '0028_alter_categorymodemapping_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('syncing', '同步中'), ('succeeded', '同步成功'), ('failed', '同步失败')], default='syncing', help_text='同步状态', max_length=20, verbose_name='同步状态')),
                ('device_count', models.IntegerField(help_text='设备总数量', verbose_name='设备总数量')),
                ('added_count', models.IntegerField(help_text='已添加数量', verbose_name='已添加数量')),
                ('sync_count', models.IntegerField(default=0, help_text='实际同步数量', verbose_name='实际同步数量')),
                ('operate_time', models.DateTimeField(default=django.utils.timezone.now, help_text='操作时间', verbose_name='操作时间')),
                ('finish_time', models.DateTimeField(blank=True, help_text='完成时间', null=True, verbose_name='完成时间')),
                ('operator', models.ForeignKey(blank=True, help_text='操作人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('project', models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.CASCADE, related_name='device_sync_records', to='projects.projects', verbose_name='项目')),
            ],
            options={
                'verbose_name': '设备同步记录',
                'verbose_name_plural': '设备同步记录',
            },
        ),
    ]
