# Generated by Django 4.2.16 on 2025-01-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0029_devicesyncrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesyncrecord',
            name='category_ids',
            field=models.TextField(default='', help_text='同步设备类型ID', verbose_name='同步设备类型ID'),
        ),
    ]
