# Generated by Django 4.2.16 on 2025-01-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0030_devicesyncrecord_category_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesyncrecord',
            name='remark',
            field=models.CharField(blank=True, help_text='备注', max_length=200, null=True, verbose_name='备注'),
        ),
    ]
