# Generated by Django 4.2.16 on 2025-01-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0031_devicesyncrecord_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='belong_unit',
            field=models.CharField(blank=True, help_text='EZt设备所属分组', max_length=100, null=True, verbose_name='EZt设备所属分组'),
        ),
    ]
