# Generated by Django 4.2.16 on 2025-02-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0032_device_belong_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodemapping',
            name='device_type',
            field=models.CharField(choices=[('air_cond', '中央空调监控'), ('personnel_sensor', '人体存在传感器'), ('space_tight_sensor', '门窗传感器'), ('electric_meter', '电表'), ('iot_breaker', '物联网断路器'), ('power_source', '进线电源'), ('hidden_danger_monitor', '隐患监测'), ('el_monitor_instrument', '三相电力仪表'), ('transformer', '变压器电力监测'), ('tf_temperature_monitor', '变压器温度监测'), ('light_monitor', '照明灯具')], help_text='MCP设备模型', max_length=30, verbose_name='MCP设备模型'),
        ),
    ]
