# Generated by Django 4.2.19 on 2025-03-13 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0033_alter_categorymodemapping_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceControlLogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(help_text='应用菜单Key', max_length=100, verbose_name='应用菜单Key')),
                ('operation_name', models.CharField(default='', help_text='操作名称', max_length=200, verbose_name='操作名称')),
                ('set_msg', models.JSONField(help_text='控制指令信息', verbose_name='控制指令信息')),
                ('operation_time', models.DateTimeField(default=django.utils.timezone.now, help_text='执行时间', verbose_name='操作时间')),
                ('devices', models.ManyToManyField(help_text='操作设备', related_name='device_control_logs', to='equipments.device', verbose_name='操作设备')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_control_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '设备操控日志',
                'verbose_name_plural': '设备操控日志',
            },
        ),
    ]
