# Generated by Django 4.2.20 on 2025-03-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0034_devicecontrollogging'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='alarm_status',
            field=models.CharField(choices=[('normal', '正常'), ('pending', '告警待定'), ('alerting', '告警')], default='normal', help_text='告警状态', max_length=20, verbose_name='告警状态'),
        ),
    ]
