# Generated by Django 4.2.20 on 2025-08-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0041_alter_categorymodemapping_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='scene_action',
            field=models.BooleanField(default=True, help_text='是否参与场景动作', verbose_name='是否参与场景动作'),
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='scene_condition',
            field=models.BooleanField(default=True, help_text='是否参与场景条件', verbose_name='是否参与场景条件'),
        ),
    ]
