# Generated by Django 4.2.20 on 2025-08-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0042_devicecategory_scene_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='key',
            field=models.CharField(blank=True, help_text='EZt设备类型唯一标识', max_length=16, null=True, unique=True, verbose_name='EZt设备类型唯一标识'),
        ),
    ]
