# Generated by Django 4.2.20 on 2025-10-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0044_alter_categorymodemapping_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='serial_id',
            field=models.CharField(blank=True, help_text='设备序列号, 在同一个设备类型下唯一', max_length=64, null=True, verbose_name='设备序列号'),
        ),
    ]
