# Generated by Django 4.2.16 on 2024-12-18 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device_models', '0007_iotbreaker'),
        ('projects', '0011_projectmembers_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotBreakerTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='节点名称', max_length=20, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('group', '分组'), ('device', '设备')], db_index=True, default='group', help_text='节点类型', max_length=10, verbose_name='节点类型')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('org', models.ForeignKey(blank=True, help_text='所属组织', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_iot_breakers', to='projects.orgtree', verbose_name='所属组织')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='父节点', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='iot_breakers.iotbreakertreenode', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '物联网短路器-树结构',
                'verbose_name_plural': '物联网短路器-树结构',
            },
        ),
        migrations.CreateModel(
            name='IotBreakerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('iot_breaker', models.ForeignKey(help_text='空调', on_delete=django.db.models.deletion.CASCADE, related_name='iot_breaker_device', to='device_models.iotbreaker', verbose_name='空调')),
                ('node', models.ForeignKey(blank=True, help_text='分组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_iot_breakers', to='iot_breakers.iotbreakertreenode', verbose_name='分组')),
            ],
            options={
                'verbose_name': '物联网短路器-断路器设备',
                'verbose_name_plural': '物联网短路器-断路器设备',
            },
        ),
    ]
