# Generated by Django 4.2.16 on 2024-12-18 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0007_iotbreaker'),
        ('iot_breakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotbreakerdevice',
            name='iot_breaker',
            field=models.ForeignKey(help_text='物联网断路器', on_delete=django.db.models.deletion.CASCADE, related_name='iot_breaker_device', to='device_models.iotbreaker', verbose_name='物联网断路器'),
        ),
    ]
