# Generated by Django 4.2.16 on 2024-12-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_breakers', '0002_alter_iotbreakerdevice_iot_breaker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotbreakerdevice',
            options={'verbose_name': '物联网短路器_断路器设备', 'verbose_name_plural': '物联网短路器_断路器设备'},
        ),
        migrations.AlterModelOptions(
            name='iotbreakertreenode',
            options={'verbose_name': '物联网短路器_树结构', 'verbose_name_plural': '物联网短路器_树结构'},
        ),
    ]
