# Generated by Django 4.2.16 on 2024-12-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_breakers', '0003_alter_iotbreakerdevice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotbreakerdevice',
            options={'verbose_name': '物联网断路器-断路器设备', 'verbose_name_plural': '物联网断路器-断路器设备'},
        ),
        migrations.AlterModelOptions(
            name='iotbreakertreenode',
            options={'verbose_name': '物联网断路器-树结构', 'verbose_name_plural': '物联网断路器-树结构'},
        ),
    ]
