# Generated by Django 4.2.16 on 2024-12-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_breakers', '0004_alter_iotbreakerdevice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotbreakertreenode',
            name='name',
            field=models.CharField(blank=True, help_text='节点名称', max_length=60, verbose_name='节点名称'),
        ),
    ]
