# Generated by Django 4.2.16 on 2025-01-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot_breakers', '0005_alter_iotbreakertreenode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotbreakerdevice',
            name='node',
            field=models.OneToOneField(blank=True, help_text='分组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_iot_breaker', to='iot_breakers.iotbreakertreenode', verbose_name='分组'),
        ),
    ]
