# Generated by Django 4.2.16 on 2025-02-27 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0033_alter_categorymodemapping_device_type'),
        ('iot_breakers', '0006_alter_iotbreakerdevice_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotbreakertreenode',
            name='device',
            field=models.ForeignKey(blank=True, help_text='关联设备', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.device', verbose_name='关联设备'),
        ),
    ]
