# Generated by Django 4.2.20 on 2025-04-01 14:18

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iot_breakers', '0007_iotbreakertreenode_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotbreakertreenode',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='父节点', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='iot_breakers.iotbreakertreenode', verbose_name='父节点'),
        ),
    ]
