# Generated by Django 4.2.20 on 2025-04-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0033_environmentmonitor'),
        ('iot_breakers', '0008_alter_iotbreakertreenode_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotbreakertreenode',
            name='iot_breaker',
            field=models.ForeignKey(blank=True, help_text='物联网断路器', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iot_breaker_nodes', to='device_models.iotbreaker', verbose_name='物联网断路器'),
        ),
    ]
