# Generated by Django 4.2.16 on 2024-09-12 16:31

import backend.apps.common.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(default='匿名', help_text='中文名', max_length=50, verbose_name='中文名')),
                ('mobile', backend.apps.common.fields.CharNullField(blank=True, help_text='手机号', max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('email', backend.apps.common.fields.CharNullField(blank=True, help_text='邮箱', max_length=50, null=True, unique=True, verbose_name='邮箱')),
                ('avatar', models.TextField(blank=True, help_text='用户头像', null=True, verbose_name='用户头像')),
                ('remark', models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=150, null=True, verbose_name='地址')),
                ('is_sys', models.BooleanField(default=True, help_text='是否系统内用户', verbose_name='是否系统内用户')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已删除', verbose_name='是否已删除')),
                ('token', models.CharField(blank=True, help_text='机器用户可基于token访问API', max_length=20, null=True)),
                ('default_style', models.TextField(blank=True, help_text='默认样式', null=True, verbose_name='默认样式')),
                ('creator', models.ForeignKey(blank=True, help_text='创建者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('default_city', models.ForeignKey(blank=True, help_text='默认城市', null=True, on_delete=django.db.models.deletion.SET_NULL, to='areas.area')),
                ('default_project', models.ForeignKey(blank=True, help_text='默认项目', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projects', verbose_name='默认项目')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
