# Generated by Django 4.2.20 on 2025-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_updated',
            field=models.DateTimeField(blank=True, help_text='记录用户信息最后修改时间', null=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(blank=True, default=None, help_text='跨系统用户关联的唯一标识', null=True, verbose_name='UUID'),
        ),
    ]
