# Generated by Django 4.2.16 on 2024-09-12 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('app_type', models.CharField(choices=[('project', '项目'), ('org', '机构'), ('station', '站点')], help_text='应用类型', max_length=20, verbose_name='应用类型')),
                ('category', models.CharField(help_text='菜单分类', max_length=50, verbose_name='菜单分类')),
                ('menu_name', models.CharField(help_text='菜单名称', max_length=30, verbose_name='菜单名称')),
                ('router_path', models.CharField(help_text='菜单路径', max_length=100, verbose_name='菜单路径')),
                ('app_name', models.CharField(blank=True, help_text='应用名', max_length=50, null=True, verbose_name='应用名')),
            ],
            options={
                'verbose_name': '应用菜单管理表',
                'verbose_name_plural': '应用菜单管理表',
            },
        ),
        migrations.CreateModel(
            name='PermissionManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='菜单大类')),
                ('permissions', models.ManyToManyField(related_name='manage_permissions', to='auth.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '权限管理类',
                'verbose_name_plural': '权限管理类',
            },
        ),
        migrations.CreateModel(
            name='GroupManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='角色')),
                ('manage_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manage_groups', to='auth.group', verbose_name='管理角色')),
            ],
            options={
                'verbose_name': '角色管理',
                'verbose_name_plural': '角色管理',
            },
        ),
        migrations.CreateModel(
            name='GroupDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='角色描述', null=True, verbose_name='角色描述')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_detail', to='auth.group', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色明细表',
                'verbose_name_plural': '角色明细表',
            },
        ),
    ]
