# Generated by Django 4.2.16 on 2024-11-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_projects_menus_and_more'),
        ('custom_perm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppMenus',
        ),
    ]
