# Generated by Django 4.2.20 on 2025-08-05 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0023_alter_projects_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='场景名称', max_length=100, verbose_name='场景名称')),
                ('description', models.TextField(blank=True, help_text='场景描述', null=True, verbose_name='场景描述')),
                ('project_key', models.CharField(help_text='Ezt项目project_key 通常以"PR_"开头，如"PR_xxxxxxxxxx', max_length=30, verbose_name=' Ezt项目project_key')),
                ('scene_id', models.IntegerField(help_text='EztCloud场景ID', verbose_name=' EztCloud场景ID')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('cfg_info', models.JSONField(blank=True, help_text='场景配置详情', null=True, verbose_name='场景配置详情')),
                ('scene_devices_data', models.JSONField(blank=True, help_text='场景配置详情', null=True, verbose_name='场景配置详情')),
                ('trigger_type', models.CharField(blank=True, help_text='触发类型', max_length=100, null=True, verbose_name='触发类型')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('org', models.ForeignKey(blank=True, help_text='所属组织', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_scenes', to='projects.orgtree', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '场景设置',
                'verbose_name_plural': '场景设置',
            },
        ),
    ]
