# Generated by Django 4.2.20 on 2026-03-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='''
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'scenes_sceneconfig'
                              AND column_name = 'project_key'
                        )
                        AND NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'scenes_sceneconfig'
                              AND column_name = 'project_id'
                        ) THEN
                            ALTER TABLE scenes_sceneconfig RENAME COLUMN project_key TO project_id;
                        END IF;
                    END
                    $$;
                    ''',
                    reverse_sql='''
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'scenes_sceneconfig'
                              AND column_name = 'project_id'
                        )
                        AND NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'scenes_sceneconfig'
                              AND column_name = 'project_key'
                        ) THEN
                            ALTER TABLE scenes_sceneconfig RENAME COLUMN project_id TO project_key;
                        END IF;
                    END
                    $$;
                    ''',
                )
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='sceneconfig',
                    old_name='project_key',
                    new_name='project_id',
                ),
            ],
        ),
        migrations.AddField(
            model_name='sceneconfig',
            name='interval_seconds',
            field=models.PositiveIntegerField(default=60, help_text='重发间隔(1-300秒)', verbose_name='重发间隔(1-300秒)'),
        ),
        migrations.AddField(
            model_name='sceneconfig',
            name='resend_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='重发次数(0-3次)', verbose_name='重发次数'),
        ),
    ]
