# Generated by Django 4.2.20 on 2025-04-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0032_switchmonitor'),
        ('lighting_monitor', '0002_lightmonitornode_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightdevice',
            name='light_monitor',
            field=models.ForeignKey(help_text='设备模型照明设备', on_delete=django.db.models.deletion.CASCADE, related_name='lighting_devices', to='device_models.lightmonitor', verbose_name='设备模型照明设备'),
        ),
    ]
