# Generated by Django 4.2.20 on 2025-04-01 14:18

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lighting_monitor', '0003_alter_lightdevice_light_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightmonitornode',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='父节点', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='lighting_monitor.lightmonitornode', verbose_name='父节点'),
        ),
    ]
