# Generated by Django 4.2.20 on 2025-04-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0033_environmentmonitor'),
        ('lighting_monitor', '0004_alter_lightmonitornode_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightmonitornode',
            name='light_monitor',
            field=models.ForeignKey(blank=True, help_text='设备模型照明设备', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lighting_monitor_nodes', to='device_models.lightmonitor', verbose_name='设备模型照明设备'),
        ),
    ]
