# Generated by Django 4.2.16 on 2024-12-25 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0011_projectmembers_ordering'),
        ('device_models', '0014_elmonitorinstrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='节点名称', max_length=60, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('group', '分组'), ('device', '设备')], db_index=True, default='group', help_text='节点类型', max_length=10, verbose_name='节点类型')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('org', models.ForeignKey(blank=True, help_text='所属组织', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_el_branches', to='projects.orgtree', verbose_name='所属组织')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='父节点', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='el_branch.branchtreenode', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '回路配置-树结构',
                'verbose_name_plural': '回路配置-树结构',
            },
        ),
        migrations.CreateModel(
            name='ElInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('el_monitor', models.ForeignKey(help_text='电气监测仪表', on_delete=django.db.models.deletion.CASCADE, related_name='el_instruments', to='device_models.elmonitorinstrument', verbose_name='电气监测仪表')),
                ('node', models.ForeignKey(blank=True, help_text='分组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_el_instruments', to='el_branch.branchtreenode', verbose_name='分组')),
            ],
            options={
                'verbose_name': '回路配置-电气仪表',
                'verbose_name_plural': '回路配置-电气仪表',
            },
        ),
    ]
