# Generated by Django 4.2.16 on 2024-12-25 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('el_branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elinstrument',
            name='node',
            field=models.OneToOneField(blank=True, help_text='分组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_el_instrument', to='el_branch.branchtreenode', verbose_name='分组'),
        ),
    ]
