# Generated by Django 4.2.16 on 2024-12-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectmembers_ordering'),
        ('el_branch', '0002_alter_elinstrument_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchtreenode',
            name='org',
            field=models.ForeignKey(blank=True, help_text='所属组织', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_branch_nodes', to='projects.orgtree', verbose_name='所属组织'),
        ),
    ]
