# Generated by Django 4.2.20 on 2025-04-01 14:18

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('el_branch', '0004_branchtreenode_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchtreenode',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='父节点', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='el_branch.branchtreenode', verbose_name='父节点'),
        ),
    ]
