# Generated by Django 4.2.20 on 2025-04-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0033_environmentmonitor'),
        ('el_branch', '0005_alter_branchtreenode_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchtreenode',
            name='el_monitor',
            field=models.ForeignKey(blank=True, help_text='电气监测仪表', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='el_instrument_nodes', to='device_models.elmonitorinstrument', verbose_name='电气监测仪表'),
        ),
    ]
