# Generated by Django 4.2.20 on 2025-09-02 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device_models', '0036_prepaidelectricmeter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0023_alter_projects_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaidElMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='电费电价(元/度)', max_digits=8, verbose_name='电费电价(元/度)')),
                ('waring_amount', models.DecimalField(decimal_places=2, help_text='预警金额(元)', max_digits=10, verbose_name='预警金额(元)')),
                ('trip_amount', models.DecimalField(blank=True, decimal_places=2, help_text='跳闸金额(元)', max_digits=10, null=True, verbose_name='跳闸金额(元)')),
                ('surplus', models.DecimalField(decimal_places=6, default=0, help_text='电费余额(元)', max_digits=16, verbose_name='电费余额(元)')),
                ('settle_time', models.DateTimeField(blank=True, help_text='余额结算时间', null=True, verbose_name='余额结算时间')),
                ('first_epi', models.FloatField(blank=True, help_text='电表初始码值(度)', null=True, verbose_name='电表初始码值(度)')),
                ('recharge_amount', models.DecimalField(decimal_places=2, default=0, help_text='租客累计充值金额(元)', max_digits=15, verbose_name='租客累计充值金额(元)')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('org', models.ForeignKey(help_text='所属组织', on_delete=django.db.models.deletion.PROTECT, to='projects.orgtree', verbose_name='所属组织')),
                ('prepaid_el_meter', models.OneToOneField(help_text='预付费电表', on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_el_device', to='device_models.prepaidelectricmeter', verbose_name='预付费电表')),
            ],
            options={
                'verbose_name': '预付费系统-电表',
                'verbose_name_plural': '预付费系统-电表',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='金额(元)', max_digits=13, verbose_name='金额(元)')),
                ('operating_time', models.DateTimeField(default=django.utils.timezone.now, help_text='提现时间', verbose_name='提现时间')),
                ('surplus', models.DecimalField(decimal_places=2, help_text='余额(元)', max_digits=13, verbose_name='余额(元)')),
                ('order_id', models.CharField(help_text='单号', max_length=100, unique=True, verbose_name='单号')),
                ('org', models.ForeignKey(help_text='所属组织', on_delete=django.db.models.deletion.CASCADE, to='projects.orgtree', verbose_name='所属组织')),
                ('user', models.ForeignKey(help_text='提现用户', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='提现用户')),
            ],
            options={
                'verbose_name': '预付费系统-提现记录',
                'verbose_name_plural': '预付费系统-提现记录',
            },
        ),
        migrations.CreateModel(
            name='TenantElMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('el_meter', models.ForeignKey(help_text='预付费电表', on_delete=django.db.models.deletion.PROTECT, to='el_prepayment_servers.prepaidelmeter', verbose_name='预付费电表')),
                ('user', models.ForeignKey(help_text='租客', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='租客')),
            ],
            options={
                'verbose_name': '预付费系统-租客电表',
                'verbose_name_plural': '预付费系统-租客电表',
            },
        ),
        migrations.CreateModel(
            name='RevenueDailyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic_date', models.DateField(help_text='统计日期', verbose_name='统计日期')),
                ('amount', models.DecimalField(decimal_places=2, help_text='收益金额(元)', max_digits=13, verbose_name='收益金额(元)')),
                ('el_meter', models.ForeignKey(help_text='预付费电表', on_delete=django.db.models.deletion.PROTECT, to='el_prepayment_servers.prepaidelmeter', verbose_name='预付费电表')),
            ],
            options={
                'verbose_name': '预付费系统-电表每日收益统计',
                'verbose_name_plural': '预付费系统-电表每日收益统计',
            },
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='订单编号', max_length=100, unique=True, verbose_name='订单编号')),
                ('payment_type', models.CharField(choices=[('wx', '微信支付'), ('off_line', '线下充值')], help_text='充值方式', max_length=20, verbose_name='充值方式')),
                ('surplus', models.DecimalField(decimal_places=6, help_text='充值后余额(元)', max_digits=16, verbose_name='充值后余额(元)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='充值金额(元)', max_digits=13, verbose_name='充值金额(元)')),
                ('prepay_id', models.CharField(blank=True, help_text='支付单号', max_length=100, null=True, verbose_name='支付单号')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='充值时间')),
                ('el_meter', models.ForeignKey(help_text='预付费电表', on_delete=django.db.models.deletion.PROTECT, related_name='recharge_records', to='el_prepayment_servers.prepaidelmeter', verbose_name='预付费电表')),
                ('user', models.ForeignKey(help_text='充值用户', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='充值用户')),
            ],
            options={
                'verbose_name': '预付费系统-充值记录',
                'verbose_name_plural': '预付费系统-充值记录',
            },
        ),
        migrations.CreateModel(
            name='PrepaidOrgCfg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default='0.50', help_text='默认电费电价(元/度)', max_digits=8, verbose_name='默认电费电价(元/度)')),
                ('waring_amount', models.DecimalField(decimal_places=2, default=50, help_text='默认预警金额(元)', max_digits=10, verbose_name='默认预警金额(元)')),
                ('trip_amount', models.DecimalField(blank=True, decimal_places=2, help_text='跳闸金额(元)', max_digits=10, null=True, verbose_name='跳闸金额(元)')),
                ('recharge_amount', models.DecimalField(decimal_places=2, default=0, help_text='租客累计充值金额(元)', max_digits=15, verbose_name='租客累计充值金额(元)')),
                ('withdrawn_amount', models.DecimalField(decimal_places=2, default=0, help_text='已提现金额(元)', max_digits=15, verbose_name='已提现金额(元)')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('org', models.OneToOneField(help_text='所属组织', on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_cfg', to='projects.orgtree', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '预付费系统-组织配置',
                'verbose_name_plural': '预付费系统-组织配置',
            },
        ),
        migrations.CreateModel(
            name='MeterReadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_epi', models.FloatField(help_text='抄表起始码值(度)', verbose_name='抄表起始码值(度)')),
                ('end_epi', models.FloatField(help_text='抄表截止码值(度)', verbose_name='抄表截止码值(度)')),
                ('used_el', models.FloatField(help_text='使用电量(度)', verbose_name='使用电量(度)')),
                ('price', models.DecimalField(decimal_places=2, help_text='电费电价(元/度)', max_digits=8, verbose_name='电费电价(元/度)')),
                ('used_amount', models.DecimalField(decimal_places=6, help_text='使用电费(元)', max_digits=16, verbose_name='使用电费(元)')),
                ('surplus', models.DecimalField(decimal_places=6, help_text='电费余额(元)', max_digits=16, verbose_name='电费余额(元)')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='扣费时间')),
                ('el_meter', models.ForeignKey(help_text='预付费电表', on_delete=django.db.models.deletion.PROTECT, to='el_prepayment_servers.prepaidelmeter', verbose_name='预付费电表')),
            ],
            options={
                'verbose_name': '预付费系统-抄表记录',
                'verbose_name_plural': '预付费系统-抄表记录',
            },
        ),
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='事件类型', max_length=10, verbose_name='事件类型')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('el_meter', models.ForeignKey(help_text='预付费电表', on_delete=django.db.models.deletion.PROTECT, related_name='event_records', to='el_prepayment_servers.prepaidelmeter', verbose_name='预付费电表')),
            ],
            options={
                'verbose_name': '预付费系统-事件记录',
                'verbose_name_plural': '预付费系统-事件记录',
            },
        ),
        migrations.CreateModel(
            name='ElDailyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic_date', models.DateField(help_text='统计日期', verbose_name='统计日期')),
                ('used_el', models.FloatField(help_text='耗电量(度)', verbose_name='耗电量(度)')),
                ('el_meter', models.ForeignKey(help_text='预付费电表', on_delete=django.db.models.deletion.PROTECT, to='el_prepayment_servers.prepaidelmeter', verbose_name='预付费电表')),
            ],
            options={
                'verbose_name': '预付费系统-电表每日耗电统计',
                'verbose_name_plural': '预付费系统-电表每日耗电统计',
            },
        ),
    ]
