# Generated by Django 4.2.20 on 2025-09-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0044_alter_categorymodemapping_device_type'),
        ('device_models', '0036_prepaidelectricmeter'),
        ('el_prepayment_servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventrecord',
            options={'ordering': ('-id',), 'verbose_name': '预付费系统-事件记录', 'verbose_name_plural': '预付费系统-事件记录'},
        ),
        migrations.AlterModelOptions(
            name='meterreadrecord',
            options={'ordering': ('-id',), 'verbose_name': '预付费系统-抄表记录', 'verbose_name_plural': '预付费系统-抄表记录'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrecords',
            options={'ordering': ('-id',), 'verbose_name': '预付费系统-提现记录', 'verbose_name_plural': '预付费系统-提现记录'},
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='device',
            field=models.ForeignKey(blank=True, help_text='关联设备', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.device', verbose_name='关联设备'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='device',
            field=models.ForeignKey(blank=True, help_text='关联设备', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipments.device', verbose_name='关联设备'),
        ),
        migrations.AlterField(
            model_name='prepaidelmeter',
            name='prepaid_el_meter',
            field=models.OneToOneField(blank=True, help_text='预付费电表', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_el_device', to='device_models.prepaidelectricmeter', verbose_name='预付费电表'),
        ),
    ]
