# Generated by Django 4.2.20 on 2025-09-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_orgtree_is_deleted'),
        ('el_prepayment_servers', '0002_alter_eventrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidorgcfg',
            name='org',
            field=models.OneToOneField(help_text='所属组织', on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_cfg', to='projects.orgtree', verbose_name='所属组织'),
        ),
    ]
