# Generated by Django 4.2.20 on 2025-09-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0036_prepaidelectricmeter'),
        ('el_prepayment_servers', '0003_alter_prepaidorgcfg_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidelmeter',
            name='del_device_key',
            field=models.CharField(blank=True, help_text='设备key', max_length=20, null=True, verbose_name='设备key'),
        ),
        migrations.AlterField(
            model_name='prepaidelmeter',
            name='prepaid_el_meter',
            field=models.OneToOneField(blank=True, help_text='预付费电表', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepaid_el_device', to='device_models.prepaidelectricmeter', verbose_name='预付费电表'),
        ),
    ]
