# Generated by Django 4.2.20 on 2025-09-09 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('el_prepayment_servers', '0004_prepaidelmeter_del_device_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(help_text='商户订单号', max_length=32, unique=True, verbose_name='商户订单号')),
                ('trade_state', models.CharField(choices=[('PENDING', '待支付'), ('SUCCESS ', '支付成功'), ('REFUND', '转入退款'), ('NOTPAY', '未支付'), ('CLOSED', '已关闭'), ('REVOKED', '已撤销'), ('USERPAYING', '用户支付中'), ('PAYERROR', '支付失败')], default='PENDING', help_text='订单交易状态', max_length=20, verbose_name='订单交易状态')),
                ('trade_type', models.CharField(blank=True, choices=[('JSAPI', '公众号、小程序'), ('NATIVE', 'Native'), ('APP', 'APP'), ('MICROPAY', '付款码支付'), ('MWEB', 'H5支付'), ('FACEPAY', '刷脸支付')], help_text='交易类型', max_length=20, null=True, verbose_name='交易类型')),
                ('payment_type', models.CharField(choices=[('wx', '微信支付'), ('zfb', '支付宝'), ('bank', '银行卡')], default='wx', help_text='支付方式', max_length=20, verbose_name='支付方式')),
                ('pay_time', models.DateTimeField(blank=True, help_text='支付时间', null=True, verbose_name='支付时间')),
                ('amount', models.DecimalField(decimal_places=2, help_text='充值金额(元)', max_digits=13, verbose_name='充值金额(元)')),
                ('remark', models.CharField(blank=True, help_text='订单备注', max_length=200, null=True, verbose_name='订单备注')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('el_meter', models.ForeignKey(blank=True, help_text='预付费电表', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_orders', to='el_prepayment_servers.prepaidelmeter', verbose_name='预付费电表')),
                ('user', models.ForeignKey(help_text='充值用户', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='充值用户')),
            ],
            options={
                'verbose_name': '预付费系统-充值订单',
                'verbose_name_plural': '预付费系统-充值订单',
                'ordering': ('-id',),
            },
        ),
    ]
