# Generated by Django 4.2.20 on 2025-09-11 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0018_remove_domain_we_mch_private_key'),
        ('el_prepayment_servers', '0005_rechargeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargeorder',
            name='domain',
            field=models.ForeignKey(blank=True, default=None, help_text='服务域名', null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_servers.domain'),
        ),
    ]
