# Generated by Django 4.2.20 on 2025-09-11 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0018_remove_domain_we_mch_private_key'),
        ('el_prepayment_servers', '0006_rechargeorder_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrecords',
            name='domain',
            field=models.ForeignKey(blank=True, default=None, help_text='服务域名', null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_servers.domain'),
        ),
        migrations.AddField(
            model_name='withdrawalrecords',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='是否完结', verbose_name='是否完结'),
        ),
        migrations.AddField(
            model_name='withdrawalrecords',
            name='remark',
            field=models.CharField(blank=True, help_text='订单备注', max_length=200, null=True, verbose_name='订单备注'),
        ),
        migrations.AddField(
            model_name='withdrawalrecords',
            name='state',
            field=models.CharField(choices=[('ACCEPTED', '转账已受理'), ('WAIT_USER_CONFIRM ', '待收款用户确认'), ('TRANSFERING', '转账中'), ('SUCCESS', '转账成功'), ('FAIL', '转账失败'), ('CANCELLED', '转账已撤销')], default='ACCEPTED', help_text='单据状态', max_length=20, verbose_name='单据状态'),
        ),
        migrations.AddField(
            model_name='withdrawalrecords',
            name='transfer_bill_no',
            field=models.CharField(blank=True, help_text='微信转账单号', max_length=100, null=True, unique=True, verbose_name='微信转账单号'),
        ),
        migrations.AddField(
            model_name='withdrawalrecords',
            name='update_time',
            field=models.DateTimeField(blank=True, help_text='最后一次状态变更时', null=True, verbose_name='最后一次状态变更时'),
        ),
        migrations.AlterField(
            model_name='withdrawalrecords',
            name='order_id',
            field=models.CharField(help_text='商户单号', max_length=100, unique=True, verbose_name='商户单号'),
        ),
    ]
