# Generated by Django 4.2.20 on 2025-09-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_prepayment_servers', '0007_withdrawalrecords_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargeorder',
            name='trade_state',
            field=models.CharField(choices=[('PENDING', '待支付'), ('SUCCESS ', '支付成功'), ('REFUND', '转入退款'), ('NOTPAY', '未支付'), ('CLOSED', '已关闭'), ('REVOKED', '已撤销'), ('USERPAYING', '用户支付中'), ('PAYERROR', '支付失败')], db_index=True, default='PENDING', help_text='订单交易状态', max_length=20, verbose_name='订单交易状态'),
        ),
        migrations.AlterField(
            model_name='withdrawalrecords',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False, help_text='是否完结', verbose_name='是否完结'),
        ),
    ]
