# Generated by Django 4.2.20 on 2025-09-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_prepayment_servers', '0008_alter_rechargeorder_trade_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerecord',
            name='remark',
            field=models.CharField(blank=True, help_text='备注', max_length=200, null=True, verbose_name='备注'),
        ),
    ]
