# Generated by Django 4.2.20 on 2025-09-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_prepayment_servers', '0009_rechargerecord_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eldailystatistic',
            options={'verbose_name': '预付费系统-电表每日统计', 'verbose_name_plural': '预付费系统-电表每日统计'},
        ),
        migrations.AddField(
            model_name='eldailystatistic',
            name='used_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='电费(元)', max_digits=13, verbose_name='电费(元)'),
        ),
        migrations.DeleteModel(
            name='RevenueDailyStatistic',
        ),
    ]
