# Generated by Django 4.2.20 on 2025-09-17 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('el_prepayment_servers', '0010_alter_eldailystatistic_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadrecord',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='扣费时间'),
        ),
    ]
