# Generated by Django 4.2.20 on 2025-09-28 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_orgtree_is_deleted'),
        ('el_prepayment_servers', '0011_alter_meterreadrecord_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepaidorgcfg',
            name='price',
        ),
        migrations.RemoveField(
            model_name='prepaidorgcfg',
            name='trip_amount',
        ),
        migrations.RemoveField(
            model_name='prepaidorgcfg',
            name='waring_amount',
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='deep_valley_epi',
            field=models.FloatField(blank=True, help_text='深谷电能码值(度)', null=True, verbose_name='深谷电能码值(度)'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='deep_valley_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='深谷电价(元/度)'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='flat_epi',
            field=models.FloatField(blank=True, help_text='平电能码值(度)', null=True, verbose_name='平电能码值(度)'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='flat_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='平电价(元/度)'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='is_time_of_use',
            field=models.BooleanField(default=False, help_text='是否使用复费率电费', verbose_name='是否使用复费率电费'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='on_peak_epi',
            field=models.FloatField(blank=True, help_text='峰电能码值(度)', null=True, verbose_name='峰电能码值(度)'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='on_peak_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='峰电价(元/度)'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='top_epi',
            field=models.FloatField(blank=True, help_text='尖电能码值(度)', null=True, verbose_name='尖电能码值(度)'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='top_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='尖电价(元/度)'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='used_deep_valley_epi',
            field=models.FloatField(blank=True, help_text='使用深谷电能(度)', null=True, verbose_name='使用深谷电能(度)'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='used_flat_epi',
            field=models.FloatField(blank=True, help_text='使用平电能(度)', null=True, verbose_name='使用平电能(度)'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='used_on_peak_epi',
            field=models.FloatField(blank=True, help_text='使用峰电能(度)', null=True, verbose_name='使用峰电能(度)'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='used_top_epi',
            field=models.FloatField(blank=True, help_text='使用尖电能(度)', null=True, verbose_name='使用尖电能(度)'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='used_valley_epi',
            field=models.FloatField(blank=True, help_text='使用谷电能(度)', null=True, verbose_name='使用谷电能(度)'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='valley_epi',
            field=models.FloatField(blank=True, help_text='谷电能码值(度)', null=True, verbose_name='谷电能码值(度)'),
        ),
        migrations.AddField(
            model_name='meterreadrecord',
            name='valley_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='谷电价(元/度)'),
        ),
        migrations.AddField(
            model_name='prepaidelmeter',
            name='deep_valley_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='深谷电价(元/度)'),
        ),
        migrations.AddField(
            model_name='prepaidelmeter',
            name='flat_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='平电价(元/度)'),
        ),
        migrations.AddField(
            model_name='prepaidelmeter',
            name='is_time_of_use',
            field=models.BooleanField(default=False, help_text='是否使用复费率电费', verbose_name='是否使用复费率电费'),
        ),
        migrations.AddField(
            model_name='prepaidelmeter',
            name='on_peak_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='峰电价(元/度)'),
        ),
        migrations.AddField(
            model_name='prepaidelmeter',
            name='surplus_state',
            field=models.CharField(choices=[('normal', '正常'), ('warming', '预警'), ('arrears', '欠费')], default='normal', help_text='余额状态', max_length=20, verbose_name='余额状态'),
        ),
        migrations.AddField(
            model_name='prepaidelmeter',
            name='top_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='尖电价(元/度)'),
        ),
        migrations.AddField(
            model_name='prepaidelmeter',
            name='valley_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='谷电价(元/度)'),
        ),
        migrations.AlterField(
            model_name='meterreadrecord',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='抄表时间'),
        ),
        migrations.AlterField(
            model_name='meterreadrecord',
            name='end_epi',
            field=models.FloatField(help_text='抄表截止总码值(度)', verbose_name='抄表截止总码值(度)'),
        ),
        migrations.AlterField(
            model_name='meterreadrecord',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='普通电价(元/度)', max_digits=10, null=True, verbose_name='普通电价(元/度)'),
        ),
        migrations.AlterField(
            model_name='meterreadrecord',
            name='start_epi',
            field=models.FloatField(help_text='抄表起始总码值(度)', verbose_name='抄表起始总码值(度)'),
        ),
        migrations.AlterField(
            model_name='meterreadrecord',
            name='used_el',
            field=models.FloatField(help_text='使用总电量(度)', verbose_name='使用总电量(度)'),
        ),
        migrations.AlterField(
            model_name='prepaidelmeter',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='普通电价(元/度)', max_digits=10, null=True, verbose_name='普通电价(元/度)'),
        ),
        migrations.AlterField(
            model_name='prepaidelmeter',
            name='trip_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='可透支金额(元)', max_digits=10, null=True, verbose_name='可透支金额(元)'),
        ),
        migrations.AlterField(
            model_name='prepaidelmeter',
            name='waring_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='预警金额(元)', max_digits=10, null=True, verbose_name='预警金额(元)'),
        ),
        migrations.CreateModel(
            name='PrepaidElMeterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分组名称', max_length=100, verbose_name='分组名称')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('org', models.ForeignKey(help_text='组织', on_delete=django.db.models.deletion.CASCADE, related_name='el_meter_groups', to='projects.orgtree', verbose_name='组织')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='父节点', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='el_prepayment_servers.prepaidelmetergroup', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '预付费电表-分组',
                'verbose_name_plural': '预付费电表-分组',
            },
        ),
        migrations.CreateModel(
            name='OrgPriceCfg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_time_of_use', models.BooleanField(default=False, help_text='是否使用复费率电费', verbose_name='是否使用复费率电费')),
                ('price', models.DecimalField(blank=True, decimal_places=6, help_text='普通电价(元/度)', max_digits=10, null=True, verbose_name='普通电价(元/度)')),
                ('top_price', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='尖电价(元/度)')),
                ('on_peak_price', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='峰电价(元/度)')),
                ('flat_price', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='平电价(元/度)')),
                ('valley_price', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='谷电价(元/度)')),
                ('deep_valley_price', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='深谷电价(元/度)')),
                ('name', models.CharField(help_text='名称', max_length=50, verbose_name='名称')),
                ('desc', models.TextField(blank=True, help_text='设备分组描述信息', null=True, verbose_name='设备分组描述信息')),
                ('waring_amount', models.DecimalField(blank=True, decimal_places=2, help_text='预警金额(元)', max_digits=10, null=True, verbose_name='预警金额(元)')),
                ('trip_amount', models.DecimalField(blank=True, decimal_places=2, help_text='可透支金额(元)', max_digits=10, null=True, verbose_name='可透支金额(元)')),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='是否设置为默认', verbose_name='是否设置为默认')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('org', models.ForeignKey(help_text='所属组织', on_delete=django.db.models.deletion.PROTECT, related_name='price_cfgs', to='projects.orgtree', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '预付费系统-组织电价方案',
                'verbose_name_plural': '预付费系统-组织电价方案',
            },
        ),
        migrations.AddField(
            model_name='prepaidelmeter',
            name='group',
            field=models.ForeignKey(blank=True, help_text='所属分组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_el_meters', to='el_prepayment_servers.prepaidelmetergroup', verbose_name='所属分组'),
        ),
    ]
