# Generated by Django 4.2.20 on 2025-09-29 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('el_prepayment_servers', '0012_remove_prepaidorgcfg_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgpricecfg',
            name='is_default',
        ),
        migrations.AddField(
            model_name='orgpricecfg',
            name='creator',
            field=models.ForeignKey(help_text='创建人', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='orgpricecfg',
            name='desc',
            field=models.TextField(blank=True, help_text='描述信息', null=True, verbose_name='描述信息'),
        ),
    ]
