# Generated by Django 4.2.20 on 2025-10-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_prepayment_servers', '0013_remove_orgpricecfg_is_default_orgpricecfg_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldailystatistic',
            name='used_amount',
            field=models.DecimalField(decimal_places=6, default=0, help_text='电费(元)', max_digits=18, verbose_name='电费(元)'),
        ),
    ]
