# Generated by Django 4.2.20 on 2025-10-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_prepayment_servers', '0014_alter_eldailystatistic_used_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargerecord',
            name='prepay_id',
            field=models.CharField(blank=True, help_text='由支付渠道返回的支付单号', max_length=100, null=True, verbose_name='支付单号'),
        ),
    ]
