# Generated by Django 4.2.20 on 2025-10-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_prepayment_servers', '0015_alter_rechargerecord_prepay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadrecord',
            name='end_epi',
            field=models.FloatField(blank=True, help_text='抄表截止总码值(度)', null=True, verbose_name='抄表截止总码值(度)'),
        ),
        migrations.AlterField(
            model_name='meterreadrecord',
            name='start_epi',
            field=models.FloatField(blank=True, help_text='抄表起始总码值(度)', null=True, verbose_name='抄表起始总码值(度)'),
        ),
    ]
