# Generated by Django 4.2.20 on 2025-10-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_prepayment_servers', '0016_alter_meterreadrecord_end_epi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidorgcfg',
            name='sum_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='总支付费率(元)', max_digits=13, verbose_name='总支付费率(元)'),
        ),
        migrations.AddField(
            model_name='rechargerecord',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='手续费(元)', max_digits=13, verbose_name='手续费(元)'),
        ),
        migrations.AddField(
            model_name='rechargerecord',
            name='real_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='实际到账金额(元)', max_digits=13, null=True, verbose_name='实际到账金额(元)'),
        ),
        migrations.AlterField(
            model_name='prepaidorgcfg',
            name='recharge_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='租客累计充值收益金额(元)', max_digits=15, verbose_name='租客累计充值收益金额(元)'),
        ),
    ]
