# Generated by Django 4.2.20 on 2025-10-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_prepayment_servers', '0017_prepaidorgcfg_sum_fee_rechargerecord_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidelmeter',
            name='real_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='累计收益金额(元)', max_digits=15, verbose_name='累计收益金额(元)'),
        ),
        migrations.AlterField(
            model_name='rechargerecord',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='手续费(元)', max_digits=13, null=True, verbose_name='手续费(元)'),
        ),
    ]
