# Generated by Django 4.2.20 on 2025-10-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_prepayment_servers', '0018_prepaidelmeter_real_amount_alter_rechargerecord_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidelmeter',
            name='del_device_info',
            field=models.JSONField(blank=True, help_text='删除时设备信息', null=True, verbose_name='删除时设备信息'),
        ),
    ]
