# Generated by Django 4.2.20 on 2025-10-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_prepayment_servers', '0019_prepaidelmeter_del_device_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidelmeter',
            name='used_el',
            field=models.FloatField(default=0, help_text='累计耗电量(度)', verbose_name='累计耗电量(度)'),
        ),
    ]
