# Generated by Django 4.2.20 on 2025-10-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_prepayment_servers', '0020_prepaidelmeter_used_el'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerecord',
            name='is_revenue',
            field=models.BooleanField(default=True, help_text='是否计入收益', verbose_name='是否计入收益'),
        ),
    ]
