# Generated by Django 4.2.20 on 2025-10-31 18:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('el_prepayment_servers', '0021_rechargerecord_is_revenue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenantelmeter',
            unique_together={('user', 'el_meter')},
        ),
    ]
