# Generated by Django 4.2.20 on 2025-11-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_prepayment_servers', '0022_alter_tenantelmeter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldailystatistic',
            name='used_amount',
            field=models.DecimalField(decimal_places=10, default=0, help_text='电费(元)', max_digits=22, verbose_name='电费(元)'),
        ),
        migrations.AlterField(
            model_name='meterreadrecord',
            name='surplus',
            field=models.DecimalField(decimal_places=10, help_text='电费余额(元)', max_digits=20, verbose_name='电费余额(元)'),
        ),
        migrations.AlterField(
            model_name='meterreadrecord',
            name='used_amount',
            field=models.DecimalField(decimal_places=10, help_text='使用电费(元)', max_digits=20, verbose_name='使用电费(元)'),
        ),
        migrations.AlterField(
            model_name='prepaidelmeter',
            name='surplus',
            field=models.DecimalField(decimal_places=10, default=0, help_text='电费余额(元)', max_digits=20, verbose_name='电费余额(元)'),
        ),
        migrations.AlterField(
            model_name='rechargerecord',
            name='surplus',
            field=models.DecimalField(decimal_places=10, help_text='充值后余额(元)', max_digits=20, verbose_name='充值后余额(元)'),
        ),
    ]
