# Generated by Django 4.2.20 on 2025-12-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_prepayment_servers', '0023_alter_eldailystatistic_used_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidelmeter',
            name='order',
            field=models.IntegerField(db_index=True, default=0, help_text='排序', verbose_name='排序'),
        ),
    ]
