# Generated by Django 4.2.20 on 2025-11-13 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0024_orgtree_is_deleted'),
        ('equipments', '0045_device_serial_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontCustomVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('name', models.CharField(help_text='名称', max_length=100, verbose_name='名称')),
                ('key', models.CharField(help_text='自定义变量key, front.xxx', max_length=100, verbose_name='自定义变量key')),
                ('data_type', models.CharField(choices=[('N', '数值(Number)'), ('B', '开关量(Boolean)'), ('T', '文本(String)'), ('E', '枚举(Enum)'), ('O', '键值对(Object)'), ('L', '列表(List)')], help_text='数据类型', max_length=10, verbose_name='数据类型')),
                ('data_specs', models.JSONField(blank=True, help_text='属性约束', null=True, verbose_name='属性约束')),
                ('unit', models.CharField(blank=True, help_text='单位', max_length=100, null=True, verbose_name='单位')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('org', models.ForeignKey(help_text='所属组织', on_delete=django.db.models.deletion.CASCADE, to='projects.orgtree', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '自定义变量',
                'verbose_name_plural': '自定义变量',
                'ordering': ('-id',),
                'unique_together': {('org', 'key')},
            },
        ),
        migrations.CreateModel(
            name='DeviceAttrVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('name', models.CharField(help_text='名称', max_length=100, verbose_name='名称')),
                ('attr_key', models.CharField(help_text='设备属性key', max_length=64, verbose_name='设备属性key')),
                ('key', models.CharField(help_text='属性变量key, device.DU_xxx.attr_key', max_length=100, verbose_name='属性变量key')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('device', models.ForeignKey(help_text='设备', on_delete=django.db.models.deletion.CASCADE, to='equipments.device', verbose_name='设备')),
                ('org', models.ForeignKey(help_text='所属组织', on_delete=django.db.models.deletion.CASCADE, to='projects.orgtree', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '属性变量',
                'verbose_name_plural': '属性变量',
                'ordering': ('-id',),
                'unique_together': {('org', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ApiVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('name', models.CharField(help_text='名称', max_length=100, verbose_name='名称')),
                ('key', models.CharField(help_text='API变量key, api.xxx', max_length=64, verbose_name='API变量key')),
                ('url', models.TextField(help_text='url, https://www.api.xxx', verbose_name='url')),
                ('method', models.CharField(help_text='请求方式GET, POST', max_length=10, verbose_name='请求方式')),
                ('body', models.TextField(blank=True, help_text="请求体, {'xxx': 12}", null=True, verbose_name='请求体')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('is_auto_polling', models.BooleanField(default=False, help_text='是否自动轮询', verbose_name='是否自动轮询')),
                ('polling_cycle', models.PositiveIntegerField(blank=True, help_text='轮询周期/秒', null=True, verbose_name='轮询周期/秒')),
                ('creator', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('org', models.ForeignKey(help_text='所属组织', on_delete=django.db.models.deletion.CASCADE, to='projects.orgtree', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': 'API变量',
                'verbose_name_plural': 'API变量',
                'ordering': ('-id',),
                'unique_together': {('org', 'key')},
            },
        ),
    ]
