# Generated by Django 4.2.20 on 2026-01-22 11:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_alter_orgtree_options'),
        ('configuration_cfgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyFlowDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='名称', max_length=100, verbose_name='名称')),
                ('image', models.TextField(blank=True, help_text='分布图', null=True, verbose_name='分布图')),
                ('is_polling', models.BooleanField(default=False, help_text='是否开启设备轮训', verbose_name='是否开启设备轮训')),
                ('dmap_env_devices', models.JSONField(blank=True, help_text='分布图设备', null=True, verbose_name='分布图设备')),
                ('alternative_images', models.JSONField(blank=True, help_text='分布图images', null=True, verbose_name='分布图images')),
                ('org', models.ForeignKey(help_text='所属组织', on_delete=django.db.models.deletion.CASCADE, related_name='energy_flow_distributions', to='projects.orgtree', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '能耗流向-分布图',
                'verbose_name_plural': '能耗流向-分布图',
            },
        ),
    ]
