# Generated by Django 4.2.20 on 2026-04-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration_cfgs', '0002_energyflowdistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyflowdistribution',
            name='cfg_info',
            field=models.JSONField(blank=True, help_text='分布图配置信息', null=True, verbose_name='分布图配置信息'),
        ),
    ]
