# Generated by Django 4.2.20 on 2026-05-19 03:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuration_cfgs', '0003_energyflowdistribution_cfg_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationIconCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='分类名称', max_length=50, unique=True, verbose_name='分类名称')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='排序', verbose_name='排序')),
            ],
            options={
                'verbose_name': '组态icon分类',
                'verbose_name_plural': '组态icon分类',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationImageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='分类名称', max_length=50, unique=True, verbose_name='分类名称')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='排序', verbose_name='排序')),
            ],
            options={
                'verbose_name': '组态图库分类',
                'verbose_name_plural': '组态图库分类',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='组态图片', upload_to='serve_images', verbose_name='组态图片')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='排序', verbose_name='排序')),
                ('category', models.ForeignKey(help_text='图库分类', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='configuration_cfgs.configurationimagecategory', verbose_name='图库分类')),
            ],
            options={
                'verbose_name': '组态图库',
                'verbose_name_plural': '组态图库',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(help_text='组态icon', upload_to='serve_icons', verbose_name='组态icon')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='排序', verbose_name='排序')),
                ('category', models.ForeignKey(help_text='icon分类', on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='configuration_cfgs.configurationiconcategory', verbose_name='icon分类')),
            ],
            options={
                'verbose_name': '组态icon库',
                'verbose_name_plural': '组态icon库',
            },
        ),
    ]
