# Generated by Django 4.2.16 on 2024-12-24 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0020_alter_categorymodemapping_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAlarmLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('10', '紧急'), ('20', '重要'), ('30', '普通')], help_text='告警级别', max_length=10, verbose_name='告警级别')),
                ('alarm_status', models.CharField(choices=[('normal', '正常'), ('pending', '告警待定'), ('alerting', '告警')], help_text='告警状态', max_length=20, verbose_name='告警状态')),
                ('is_restored', models.BooleanField(default=False, help_text='是否已恢复', verbose_name='是否已恢复')),
                ('alarm_rule_id', models.CharField(db_index=True, help_text='EZt告警规则ID', max_length=50, verbose_name='EZt告警规则ID')),
                ('alarm_rule_name', models.CharField(help_text='EZt告警规则名称', max_length=100, verbose_name='EZt告警规则名称')),
                ('alarm_detail', models.JSONField(blank=True, help_text='告警详情', null=True, verbose_name='告警详情')),
                ('alarm_time', models.DateTimeField(help_text='告警规则状态改变时间', verbose_name='告警规则状态改变时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_alarm_logs', to='equipments.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备告警日志',
                'verbose_name_plural': '设备告警日志',
            },
        ),
    ]
