# Generated by Django 4.2.16 on 2024-12-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicealarmlogs',
            name='is_restored',
            field=models.BooleanField(db_index=True, default=False, help_text='是否已恢复', verbose_name='是否已恢复'),
        ),
    ]
