# Generated by Django 4.2.16 on 2024-12-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0002_alter_devicealarmlogs_is_restored'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicealarmlogs',
            name='alarm_type',
            field=models.CharField(db_index=True, default='', help_text='告警类型', verbose_name='告警类型'),
        ),
    ]
