# Generated by Django 2.2.13 on 2023-08-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='服务域名', max_length=200, null=True, verbose_name='服务域名')),
                ('logo', models.ImageField(help_text='logo', upload_to='serve_logos', verbose_name='logo')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('wechat_app_id', models.CharField(help_text='微信服务号的APP ID', max_length=20, verbose_name='微信 APP ID')),
                ('wechat_app_secret', models.CharField(help_text='微信服务号的APP SECRET', max_length=32, verbose_name='微信 APP SECRET')),
            ],
            options={
                'verbose_name': '域名定制',
                'verbose_name_plural': '域名定制',
            },
        ),
    ]
