# Generated by Django 2.2.13 on 2023-08-21 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverlogo',
            options={'verbose_name': '域名', 'verbose_name_plural': '域名'},
        ),
        migrations.CreateModel(
            name='DomainUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_servers.ServerLogo', verbose_name='域名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '域名用户',
                'verbose_name_plural': '域名用户',
            },
        ),
    ]
