# Generated by Django 2.2.13 on 2023-08-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0002_auto_20230821_1410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServerLogo',
            new_name='Domain',
        ),
    ]
