# Generated by Django 2.2.13 on 2023-08-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0003_auto_20230821_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='wechat_app_id',
            new_name='we_svc_app_id',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='wechat_app_secret',
            new_name='we_svc_app_secret',
        ),
    ]
