# Generated by Django 2.2.13 on 2023-08-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0004_auto_20230821_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='we_app_app_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='微信小程序 APP ID'),
        ),
        migrations.AddField(
            model_name='domain',
            name='we_app_app_secret',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='微信小程序 APP SECRET'),
        ),
        migrations.AddField(
            model_name='domain',
            name='we_app_id',
            field=models.CharField(blank=True, default=None, max_length=18, null=True, verbose_name='微信小程序 原始ID'),
        ),
        migrations.AddField(
            model_name='domain',
            name='we_svc_id',
            field=models.CharField(blank=True, default=None, max_length=18, null=True, verbose_name='微信服务号 原始ID'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='we_svc_app_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='微信服务号 APP ID'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='we_svc_app_secret',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='微信服务号 APP SECRET'),
        ),
    ]
