# Generated by Django 2.2.13 on 2023-08-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0005_auto_20230821_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='we_app_app_id',
            new_name='weapp_app_id',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='we_app_app_secret',
            new_name='weapp_app_secret',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='we_app_id',
            new_name='weapp_id',
        ),
    ]
