# Generated by Django 2.2.13 on 2023-08-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0006_auto_20230821_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomainUser',
        ),
    ]
