# Generated by Django 2.2.28 on 2024-05-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0007_delete_domainuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='we_svc_eo_tpl_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='隐患工单消息模板ID'),
        ),
        migrations.AddField(
            model_name='domain',
            name='we_svc_error_tpl_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='告警消息模板ID'),
        ),
        migrations.AddField(
            model_name='domain',
            name='we_svc_qrcode',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='微信服务号 二维码'),
        ),
        migrations.AddField(
            model_name='domain',
            name='we_svc_warning_tpl_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='预警消息模板ID'),
        ),
    ]
