# Generated by Django 4.2.16 on 2024-12-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_servers", "0008_auto_20240510_1115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
