# Generated by Django 4.2.16 on 2024-12-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_servers", "0009_alter_domain_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domain",
            old_name="we_svc_error_tpl_id",
            new_name="we_svc_alarm_tpl_id",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="we_svc_eo_tpl_id",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="we_svc_warning_tpl_id",
        ),
    ]
