# Generated by Django 4.2.16 on 2024-12-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_servers",
            "0010_rename_we_svc_error_tpl_id_domain_we_svc_alarm_tpl_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="android_url",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="安卓端 URL",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="mobile_url",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="移动端 URL",
            ),
        ),
    ]
