# Generated by Django 4.2.16 on 2024-12-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_servers", "0011_domain_android_url_domain_mobile_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="android_url",
        ),
    ]
