# Generated by Django 4.2.16 on 2024-12-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_servers", "0012_remove_domain_android_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="api域名:端口号 或 api域名",
                max_length=200,
                null=True,
                verbose_name="名称",
            ),
        ),
    ]
