# Generated by Django 4.2.16 on 2024-12-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_servers", "0013_alter_domain_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="mobile_url",
        ),
        migrations.AddField(
            model_name="domain",
            name="mobile",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="移动端域名",
            ),
        ),
    ]
