# Generated by Django 4.2.17 on 2025-02-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0014_remove_domain_mobile_url_domain_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='logo',
            field=models.ImageField(blank=True, help_text='logo', null=True, upload_to='serve_logos', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(default='default', help_text='api域名:端口号 或 api域名', max_length=200, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
