# Generated by Django 4.2.20 on 2025-06-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0015_alter_domain_logo_alter_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='网站名称'),
        ),
    ]
