# Generated by Django 4.2.20 on 2025-09-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0016_domain_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='we_mch_id',
            field=models.CharField(blank=True, default=None, help_text='微信商户号ID', max_length=32, null=True, verbose_name='微信商户号ID'),
        ),
        migrations.AddField(
            model_name='domain',
            name='we_mch_private_key',
            field=models.TextField(blank=True, default=None, help_text='微信商户API证书私钥', null=True, verbose_name='微信商户API证书私钥'),
        ),
        migrations.AddField(
            model_name='domain',
            name='we_mch_serial_no',
            field=models.CharField(blank=True, default=None, help_text='微信商户API证书序列号', max_length=32, null=True, verbose_name='微信商户API证书序列号'),
        ),
    ]
