# Generated by Django 4.2.20 on 2025-09-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0017_domain_we_mch_id_domain_we_mch_private_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='we_mch_private_key',
        ),
    ]
