# Generated by Django 4.2.20 on 2025-10-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0018_remove_domain_we_mch_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='we_mch_serial_no',
            field=models.CharField(blank=True, default=None, help_text='微信商户API证书序列号', max_length=64, null=True, verbose_name='微信商户API证书序列号'),
        ),
    ]
