# Generated by Django 4.2.20 on 2025-10-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0019_alter_domain_we_mch_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='iam_domain',
            field=models.CharField(blank=True, help_text='统一身份认证服务域名', max_length=200, null=True, verbose_name='统一身份认证服务域名'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True, verbose_name='移动端域名'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(help_text='api域名:端口号 或 api域名', max_length=200, unique=True, verbose_name='名称'),
        ),
    ]
