# Generated by Django 4.2.20 on 2025-10-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0021_alter_domain_options_remove_domain_iam_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='wx_pay_fee',
            field=models.DecimalField(decimal_places=6, default=0.006, help_text='手续费(元)', max_digits=8, verbose_name='手续费(元)'),
        ),
    ]
