# Generated by Django 4.2.20 on 2026-03-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_servers', '0022_domain_wx_pay_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdomain',
            name='name',
            field=models.CharField(help_text='api域名 或 api域名，注意不要带端口号', max_length=200, unique=True, verbose_name='名称'),
        ),
    ]
