# Generated by Django 4.2.16 on 2024-09-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpacePhysicDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '设备物理空间树结',
                'verbose_name_plural': '设备物理空间树结',
            },
        ),
    ]
