# Generated by Django 4.2.16 on 2024-09-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('air_servers', '0001_initial'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacephysicdevice',
            name='device',
            field=models.OneToOneField(help_text='关联设备', on_delete=django.db.models.deletion.CASCADE, related_name='space_node', to='equipments.device', verbose_name='关联设备'),
        ),
    ]
