# Generated by Django 4.2.16 on 2024-09-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('air_servers', '0002_initial'),
    ]

    operations = [

    ]
