# Generated by Django 4.2.16 on 2024-10-31 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0003_remove_airconditioner_is_auto_off_and_more'),
        ('projects', '0005_orgtreeuser_orgtree_users'),
        ('air_servers', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirCondGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='节点名称', max_length=20, verbose_name='节点名称')),
                ('ordering', models.IntegerField(db_index=True, default=0, help_text='排序', verbose_name='排序')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='父节点', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='air_servers.aircondgroup', verbose_name='父节点')),
                ('station', models.ForeignKey(help_text='加油站站点', on_delete=django.db.models.deletion.CASCADE, related_name='station_groups', to='projects.station', verbose_name='加油站站点')),
            ],
            options={
                'verbose_name': '中央空调分组',
                'verbose_name_plural': '中央空调分组',
            },
        ),
        migrations.CreateModel(
            name='AirPersonnelSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('group', models.ForeignKey(blank=True, help_text='分组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_personnel_sensors', to='air_servers.aircondgroup', verbose_name='分组')),
                ('personnel_sensor', models.OneToOneField(help_text='人体存在传感器', on_delete=django.db.models.deletion.CASCADE, to='device_models.personnelsensor', verbose_name='人体存在传感器')),
            ],
            options={
                'verbose_name': '人体存在感应传感器',
                'verbose_name_plural': '人体存在感应传感器',
            },
        ),
        migrations.CreateModel(
            name='AirSpaceTightSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('group', models.ForeignKey(blank=True, help_text='分组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_space_tight_sensors', to='air_servers.aircondgroup', verbose_name='分组')),
                ('space_tight_sensor', models.OneToOneField(help_text='门窗传感器', on_delete=django.db.models.deletion.CASCADE, to='device_models.spacetightsensor', verbose_name='门窗传感器')),
            ],
            options={
                'verbose_name': '人体存在感应传感器',
                'verbose_name_plural': '人体存在感应传感器',
            },
        ),
        migrations.CreateModel(
            name='CentralAirConditioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_auto_off', models.BooleanField(default=False, help_text='是否启用无人自动关闭', verbose_name='是否启用无人自动关闭')),
                ('off_delay_minutes', models.IntegerField(blank=True, help_text='无人自动关闭延时分钟数', null=True, verbose_name='无人自动关闭延时分钟数')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('air_cond', models.OneToOneField(help_text='空调', on_delete=django.db.models.deletion.CASCADE, related_name='station_groups', to='device_models.airconditioner', verbose_name='空调')),
                ('group', models.ForeignKey(blank=True, help_text='分组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_air_conds', to='air_servers.aircondgroup', verbose_name='分组')),
            ],
            options={
                'verbose_name': '中央空调',
                'verbose_name_plural': '中央空调',
            },
        ),
        migrations.DeleteModel(
            name='SpacePhysicDevice',
        ),
    ]
