# Generated by Django 4.2.16 on 2024-11-01 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_orgtreeuser_orgtree_users'),
        ('air_servers', '0004_aircondgroup_airpersonnelsensor_airspacetightsensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airpersonnelsensor',
            name='station',
            field=models.ForeignKey(blank=True, help_text='加油站站点', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_personnel_sensors', to='projects.station', verbose_name='加油站站点'),
        ),
        migrations.AddField(
            model_name='airspacetightsensor',
            name='station',
            field=models.ForeignKey(blank=True, help_text='加油站站点', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_space_tight_sensors', to='projects.station', verbose_name='加油站站点'),
        ),
        migrations.AddField(
            model_name='centralairconditioner',
            name='station',
            field=models.ForeignKey(blank=True, help_text='加油站站点', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_air_conds', to='projects.station', verbose_name='加油站站点'),
        ),
    ]
