# Generated by Django 4.2.16 on 2024-11-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_projectmembers_level_alter_orgtree_users_and_more'),
        ('air_servers', '0005_airpersonnelsensor_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircondgroup',
            name='station',
        ),
        migrations.RemoveField(
            model_name='airpersonnelsensor',
            name='station',
        ),
        migrations.RemoveField(
            model_name='airspacetightsensor',
            name='station',
        ),
        migrations.RemoveField(
            model_name='centralairconditioner',
            name='station',
        ),
        migrations.AddField(
            model_name='aircondgroup',
            name='org',
            field=models.ForeignKey(blank=True, help_text='加油站站点', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_air_groups', to='projects.orgtree', verbose_name='加油站站点'),
        ),
    ]
