# Generated by Django 4.2.16 on 2024-11-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_servers', '0006_remove_aircondgroup_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airpersonnelsensor',
            name='group',
            field=models.ForeignKey(blank=True, help_text='分组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_personnel_sensors', to='air_servers.aircondgroup', verbose_name='分组'),
        ),
        migrations.AlterField(
            model_name='airspacetightsensor',
            name='group',
            field=models.ForeignKey(blank=True, help_text='分组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_space_tight_sensors', to='air_servers.aircondgroup', verbose_name='分组'),
        ),
        migrations.AlterField(
            model_name='centralairconditioner',
            name='group',
            field=models.ForeignKey(blank=True, help_text='分组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_air_conds', to='air_servers.aircondgroup', verbose_name='分组'),
        ),
    ]
