# Generated by Django 4.2.16 on 2024-12-06 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0004_remove_airconditioner_card_room'),
        ('air_servers', '0007_alter_airpersonnelsensor_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airpersonnelsensor',
            name='personnel_sensor',
            field=models.OneToOneField(help_text='人体存在传感器', on_delete=django.db.models.deletion.CASCADE, related_name='air_personnel_sensor', to='device_models.personnelsensor', verbose_name='人体存在传感器'),
        ),
        migrations.AlterField(
            model_name='airspacetightsensor',
            name='space_tight_sensor',
            field=models.OneToOneField(help_text='门窗传感器', on_delete=django.db.models.deletion.CASCADE, related_name='air_st_sensor', to='device_models.spacetightsensor', verbose_name='门窗传感器'),
        ),
        migrations.AlterField(
            model_name='centralairconditioner',
            name='air_cond',
            field=models.OneToOneField(help_text='空调', on_delete=django.db.models.deletion.CASCADE, related_name='central_air_cond', to='device_models.airconditioner', verbose_name='空调'),
        ),
    ]
