# Generated by Django 4.2.16 on 2024-12-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_servers', '0008_alter_airpersonnelsensor_personnel_sensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircondgroup',
            name='node_type',
            field=models.CharField(choices=[('group', '分组'), ('space', '物理空间')], db_index=True, default='group', help_text='节点类型', max_length=10, verbose_name='节点类型'),
        ),
    ]
