# Generated by Django 4.2.16 on 2024-12-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_servers', '0009_aircondgroup_node_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airpersonnelsensor',
            options={'verbose_name': '中央空调-人体存在感应传感器', 'verbose_name_plural': '中央空调-人体存在感应传感器'},
        ),
        migrations.AlterModelOptions(
            name='airspacetightsensor',
            options={'verbose_name': '中央空调-门窗传感器', 'verbose_name_plural': '中央空调-门窗传感器'},
        ),
        migrations.AlterModelOptions(
            name='centralairconditioner',
            options={'verbose_name': '中央空调-空调设备', 'verbose_name_plural': '中央空调-空调设备'},
        ),
    ]
