# Generated by Django 4.2.16 on 2024-12-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectmembers_ordering'),
        ('air_servers', '0010_alter_airpersonnelsensor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircondgroup',
            name='org',
            field=models.ForeignKey(blank=True, help_text='所属组织', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_air_groups', to='projects.orgtree', verbose_name='所属组织'),
        ),
    ]
