# Generated by Django 4.2.20 on 2025-12-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_servers', '0012_alter_airpersonnelsensor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircondgroup',
            name='node_type',
        ),
    ]
