# Generated by Django 4.2.20 on 2025-12-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_servers', '0013_remove_aircondgroup_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='airpersonnelsensor',
            name='order',
            field=models.IntegerField(db_index=True, default=0, help_text='排序', verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='airspacetightsensor',
            name='order',
            field=models.IntegerField(db_index=True, default=0, help_text='排序', verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='centralairconditioner',
            name='order',
            field=models.IntegerField(db_index=True, default=0, help_text='排序', verbose_name='排序'),
        ),
    ]
