# Generated by Django 4.2.16 on 2024-12-10 18:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0011_projectmembers_ordering'),
        ('device_models', '0005_electricmeter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='节点名称', max_length=20, verbose_name='节点名称')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='父节点', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='energy_statistics.dimensionnode', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '能耗统计维度表',
                'verbose_name_plural': '能耗统计维度表',
            },
        ),
        migrations.CreateModel(
            name='StatisticDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='统计维度名称', max_length=20, verbose_name='统计维度名称')),
                ('energy_type', models.CharField(choices=[('10', '水'), ('20', '电'), ('30', '气'), ('40', '暖')], help_text='设备分类', max_length=10, verbose_name='设备分类')),
                ('ordering', models.IntegerField(db_index=True, default=0, help_text='排序', verbose_name='排序')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('org', models.ForeignKey(blank=True, help_text='组织', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_stat_dimensions', to='projects.orgtree', verbose_name='组织')),
            ],
            options={
                'verbose_name': '能耗统计维度表',
                'verbose_name_plural': '能耗统计维度表',
            },
        ),
        migrations.CreateModel(
            name='ElectricMeterNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('+', '加'), ('-', '减')], help_text='运算关系\u200c', max_length=10, verbose_name='运算关系\u200c')),
                ('electric_meter', models.ForeignKey(help_text='电表', on_delete=django.db.models.deletion.CASCADE, related_name='electric_meter_nodes', to='device_models.electricmeter', verbose_name='电表')),
                ('node', models.ForeignKey(help_text='所属节点', on_delete=django.db.models.deletion.CASCADE, related_name='node_electric_meters', to='energy_statistics.dimensionnode', verbose_name='所属节点')),
            ],
            options={
                'verbose_name': '维度节点电表配置',
                'verbose_name_plural': '维度节点电表配置',
            },
        ),
        migrations.AddField(
            model_name='dimensionnode',
            name='stat_dimension',
            field=models.ForeignKey(blank=True, help_text='统计维度', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat_dimension_nodes', to='energy_statistics.statisticdimension', verbose_name='统计维度'),
        ),
    ]
