# Generated by Django 4.2.16 on 2024-12-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricmeternode',
            name='relation_type',
            field=models.CharField(choices=[('+', '加'), ('-', '减')], db_index=True, help_text='运算关系\u200c', max_length=10, verbose_name='运算关系\u200c'),
        ),
        migrations.AlterField(
            model_name='statisticdimension',
            name='energy_type',
            field=models.CharField(choices=[('water', '水'), ('electric', '电'), ('gas', '气'), ('heating', '暖')], help_text='设备分类', max_length=10, verbose_name='设备分类'),
        ),
    ]
