# Generated by Django 4.2.16 on 2024-12-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_statistics', '0002_alter_electricmeternode_relation_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensionnode',
            options={'verbose_name': '统计维度节点表', 'verbose_name_plural': '统计维度节点表'},
        ),
    ]
