# Generated by Django 4.2.16 on 2024-12-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_statistics', '0003_alter_dimensionnode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensionnode',
            name='name',
            field=models.CharField(blank=True, help_text='节点名称', max_length=60, verbose_name='节点名称'),
        ),
    ]
