# Generated by Django 4.2.16 on 2024-12-20 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0011_projectmembers_ordering'),
        ('device_models', '0011_networkeddevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElPowerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('org', models.ForeignKey(help_text='所属组织', on_delete=django.db.models.deletion.CASCADE, related_name='org_power_sources', to='projects.orgtree', verbose_name='所属组织')),
                ('power_source', models.ForeignKey(help_text='电源设备', on_delete=django.db.models.deletion.CASCADE, related_name='el_power_sources', to='device_models.powersource', verbose_name='电源设备')),
            ],
            options={
                'verbose_name': '电能看板-电源',
                'verbose_name_plural': '电能看板-电源',
            },
        ),
        migrations.CreateModel(
            name='ElNetWorked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('networked_device', models.ForeignKey(help_text='联网设备', on_delete=django.db.models.deletion.CASCADE, related_name='el_networked_devices', to='device_models.networkeddevice', verbose_name='联网设备')),
                ('org', models.ForeignKey(help_text='所属组织', on_delete=django.db.models.deletion.CASCADE, related_name='org_networked_devices', to='projects.orgtree', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '电能看板-联网设备',
                'verbose_name_plural': '电能看板-联网设备',
            },
        ),
        migrations.CreateModel(
            name='ElHiddenDangerMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('hidden_danger_monitor', models.ForeignKey(help_text='隐患监测备', on_delete=django.db.models.deletion.CASCADE, related_name='el_hidden_danger_monitors', to='device_models.hiddendangermonitor', verbose_name='隐患监测设备')),
                ('org', models.ForeignKey(help_text='所属组织', on_delete=django.db.models.deletion.CASCADE, related_name='org_hidden_danger_monitors', to='projects.orgtree', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '电能看板-隐患监测',
                'verbose_name_plural': '电能看板-隐患监测',
            },
        ),
        migrations.CreateModel(
            name='ElectricMeterLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('electric_meter', models.ForeignKey(help_text='电表模型', on_delete=django.db.models.deletion.CASCADE, related_name='el_meter_loads', to='device_models.electricmeter', verbose_name='电表模型')),
                ('org', models.ForeignKey(help_text='所属组织', on_delete=django.db.models.deletion.CASCADE, related_name='org_el_loads', to='projects.orgtree', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '电能看板-联网设备',
                'verbose_name_plural': '电能看板-联网设备',
            },
        ),
    ]
