# Generated by Django 4.2.16 on 2024-12-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el_energy_signboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricmeterload',
            options={'verbose_name': '电能看板-负载', 'verbose_name_plural': '电能看板-负载'},
        ),
        migrations.DeleteModel(
            name='ElNetWorked',
        ),
    ]
