# Generated by Django 4.2.16 on 2025-02-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_energy_signboards', '0002_alter_electricmeterload_options_delete_elnetworked'),
    ]

    operations = [
        migrations.AddField(
            model_name='elpowersource',
            name='ordering',
            field=models.IntegerField(db_index=True, default=0, help_text='排序', verbose_name='排序'),
        ),
    ]
