# Generated by Django 4.2.16 on 2024-12-26 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0011_projectmembers_ordering'),
        ('device_models', '0015_transformer_tftemperaturemonitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformerTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='节点名称', max_length=60, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('group', '分组'), ('device', '设备')], db_index=True, default='group', help_text='节点类型', max_length=10, verbose_name='节点类型')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('org', models.ForeignKey(blank=True, help_text='所属组织', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transformer_nodes', to='projects.orgtree', verbose_name='所属组织')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='父节点', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='transformer_monitor.transformertreenode', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '变压器监测-树结构',
                'verbose_name_plural': '变压器监测-树结构',
            },
        ),
        migrations.CreateModel(
            name='TransformerMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_type', models.CharField(blank=True, help_text='变压器类型', max_length=30, null=True, verbose_name='变压器类型')),
                ('capacity', models.CharField(blank=True, help_text='额定容量', max_length=20, null=True, verbose_name='额定容量')),
                ('code', models.CharField(blank=True, help_text='出厂编号', max_length=30, null=True, verbose_name='出厂编号')),
                ('production_date', models.DateField(blank=True, help_text='制造日期', null=True, verbose_name='制造日期')),
                ('manufacturer', models.CharField(blank=True, help_text='厂商', max_length=100, null=True, verbose_name='厂商')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('node', models.OneToOneField(blank=True, help_text='分组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_transformer_monitor', to='transformer_monitor.transformertreenode', verbose_name='分组')),
                ('temperature_monitor', models.ForeignKey(blank=True, help_text='变压器温度监测仪', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_tf_monitors', to='device_models.tftemperaturemonitor', verbose_name='变压器温度监测仪')),
                ('transformer', models.ForeignKey(help_text='变压器监测设备', on_delete=django.db.models.deletion.CASCADE, related_name='transformer_monitors', to='device_models.transformer', verbose_name='变压器监测设备')),
            ],
            options={
                'verbose_name': '变压器监测-变压器监测设备',
                'verbose_name_plural': '变压器监测-变压器监测设备',
            },
        ),
    ]
