# Generated by Django 4.2.16 on 2024-12-26 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectmembers_ordering'),
        ('transformer_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformermonitor',
            name='node',
        ),
        migrations.AddField(
            model_name='transformermonitor',
            name='org',
            field=models.ForeignKey(blank=True, help_text='所属组织', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_transformer_monitors', to='projects.orgtree', verbose_name='所属组织'),
        ),
        migrations.DeleteModel(
            name='TransformerTreeNode',
        ),
    ]
