# Generated by Django 4.2.16 on 2025-02-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer_monitor', '0002_remove_transformermonitor_node_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformermonitor',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
