# Generated by Django 4.2.16 on 2024-09-12 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('host_code', models.CharField(blank=True, help_text='主机编号', max_length=60, null=True, verbose_name='主机编号')),
                ('brand', models.CharField(blank=True, help_text='容量', max_length=50, null=True, verbose_name='空调品牌')),
                ('c_type', models.CharField(blank=True, help_text='品牌类型', max_length=50, null=True, verbose_name='品牌类型')),
                ('capacity', models.CharField(blank=True, help_text='容量', max_length=50, null=True, verbose_name='容量')),
                ('err_code', models.CharField(blank=True, help_text='故障代码', max_length=50, null=True, verbose_name='故障代码')),
                ('is_auto_off', models.BooleanField(default=False, help_text='是否启用无人自动关闭', verbose_name='是否启用无人自动关闭')),
                ('off_delay_minutes', models.IntegerField(blank=True, help_text='无人自动关闭延时分钟数', null=True, verbose_name='无人自动关闭延时分钟数')),
                ('lock_status', models.BooleanField(default=False, help_text='锁定状态', verbose_name='锁定状态')),
                ('lock_switch', models.BooleanField(default=False, help_text='是否开关锁定', verbose_name='是否开关锁定')),
                ('temp_lock', models.BooleanField(default=False, help_text='是否开关锁定', verbose_name='是否锁定温度')),
                ('t_high_limit', models.IntegerField(blank=True, help_text='温度上限', null=True, verbose_name='温度上限')),
                ('t_low_limit', models.IntegerField(blank=True, help_text='温度下限', null=True, verbose_name='温度下限')),
                ('mode_lock', models.BooleanField(default=False, help_text='是否锁定模式', verbose_name='是否锁定模式')),
                ('switch', models.CharField(blank=True, help_text='开关状态', max_length=1, null=True, verbose_name='开关状态')),
                ('mode', models.CharField(blank=True, help_text='当前模式', max_length=20, null=True, verbose_name='当前模式')),
                ('speed', models.CharField(blank=True, help_text='风速', max_length=20, null=True, verbose_name='风速')),
                ('card_room', models.CharField(blank=True, help_text='房卡状态', max_length=20, null=True, verbose_name='房卡状态')),
                ('temp_room', models.FloatField(blank=True, help_text='室内温度', null=True, verbose_name='室内温度')),
                ('temp_set', models.FloatField(blank=True, help_text='设定温度', null=True, verbose_name='设定温度')),
                ('temp_server', models.FloatField(blank=True, help_text='服务器温度', null=True, verbose_name='服务器温度')),
            ],
            options={
                'verbose_name': '空调设备数据',
                'verbose_name_plural': '空调设备数据',
            },
        ),
        migrations.CreateModel(
            name='PersonnelSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('status', models.CharField(blank=True, db_index=True, help_text='人员状态', max_length=10, null=True, verbose_name='人员状态')),
            ],
            options={
                'verbose_name': '人体存在感应传感器',
                'verbose_name_plural': '人体存在感应传感器',
            },
        ),
        migrations.CreateModel(
            name='SpaceTightSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('status', models.CharField(blank=True, db_index=True, help_text='门窗状态', max_length=10, null=True, verbose_name='门窗状态')),
            ],
            options={
                'verbose_name': '门窗传感器',
                'verbose_name_plural': '门窗传感器',
            },
        ),
    ]
