# Generated by Django 4.2.16 on 2024-10-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airconditioner',
            name='is_auto_off',
        ),
        migrations.RemoveField(
            model_name='airconditioner',
            name='off_delay_minutes',
        ),
    ]
