# Generated by Django 4.2.16 on 2024-12-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0003_remove_airconditioner_is_auto_off_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airconditioner',
            name='card_room',
        ),
    ]
