# Generated by Django 4.2.16 on 2024-12-09 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0014_alter_categorymodemapping_device_type'),
        ('device_models', '0004_remove_airconditioner_card_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('epi', models.FloatField(blank=True, help_text='有功电能', max_length=10, null=True, verbose_name='有功电能')),
                ('device', models.OneToOneField(help_text='关联设备', on_delete=django.db.models.deletion.CASCADE, related_name='electric_meter', to='equipments.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '电表',
                'verbose_name_plural': '电表',
            },
        ),
    ]
