# Generated by Django 4.2.16 on 2024-12-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0005_electricmeter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airconditioner',
            options={'verbose_name': '设备模型-空调设备', 'verbose_name_plural': '设备模型-空调设备'},
        ),
        migrations.AlterModelOptions(
            name='electricmeter',
            options={'verbose_name': '设备模型-电表', 'verbose_name_plural': '设备模型-电表'},
        ),
        migrations.AlterModelOptions(
            name='personnelsensor',
            options={'verbose_name': '设备模型-人体存在感应传感器', 'verbose_name_plural': '设备模型-人体存在感应传感器'},
        ),
        migrations.AlterModelOptions(
            name='spacetightsensor',
            options={'verbose_name': '设备模型-门窗传感器', 'verbose_name_plural': '设备模型-门窗传感器'},
        ),
    ]
