# Generated by Django 4.2.16 on 2024-12-18 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0014_alter_categorymodemapping_device_type'),
        ('device_models', '0006_alter_airconditioner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotBreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('state', models.IntegerField(blank=True, help_text='断路器状态', null=True, verbose_name='断路器状态')),
                ('switch', models.IntegerField(blank=True, help_text='断路器控制', null=True, verbose_name='断路器控制')),
                ('trip', models.IntegerField(blank=True, help_text='脱扣', null=True, verbose_name='脱扣')),
                ('lock', models.IntegerField(blank=True, help_text='脱扣', null=True, verbose_name='脱扣')),
                ('force_state', models.IntegerField(blank=True, help_text='强制合闸', null=True, verbose_name='强制合闸')),
                ('leakage_test', models.IntegerField(blank=True, help_text='漏电自检', null=True, verbose_name='漏电自检')),
                ('hz', models.FloatField(blank=True, help_text='频率', null=True, verbose_name='频率')),
                ('ma', models.FloatField(blank=True, help_text='漏电流', null=True, verbose_name='漏电流')),
                ('rated_u', models.FloatField(blank=True, help_text='额定电压', null=True, verbose_name='额定电压')),
                ('rated_i', models.FloatField(blank=True, help_text='额定电流', null=True, verbose_name='额定电流')),
                ('ua', models.FloatField(blank=True, help_text='A相电压', null=True, verbose_name='A相电压')),
                ('ub', models.FloatField(blank=True, help_text='B相电压', null=True, verbose_name='B相电压')),
                ('uc', models.FloatField(blank=True, help_text='C相电压', null=True, verbose_name='C相电压')),
                ('ib', models.FloatField(blank=True, help_text='B相电压', null=True, verbose_name='B相电压')),
                ('ic', models.FloatField(blank=True, help_text='C相电压', null=True, verbose_name='C相电压')),
                ('epi', models.FloatField(blank=True, help_text='总有功电能', null=True, verbose_name='总有功电能')),
                ('pa', models.FloatField(blank=True, help_text='A相有功功率', null=True, verbose_name='A相有功功率')),
                ('pb', models.FloatField(blank=True, help_text='B相有功功率', null=True, verbose_name='B相有功功率')),
                ('pc', models.FloatField(blank=True, help_text='C相有功功率', null=True, verbose_name='C相有功功率')),
                ('qa', models.FloatField(blank=True, help_text='A相无功功率', null=True, verbose_name='A相无功功率')),
                ('qb', models.FloatField(blank=True, help_text='B相无功功率', null=True, verbose_name='B相无功功率')),
                ('qc', models.FloatField(blank=True, help_text='C相无功功率', null=True, verbose_name='C相无功功率')),
                ('pfa', models.FloatField(blank=True, help_text='A相功率因数', null=True, verbose_name='A相功率因数')),
                ('pfb', models.FloatField(blank=True, help_text='B相功率因数', null=True, verbose_name='B相功率因数')),
                ('pfc', models.FloatField(blank=True, help_text='C相功率因数', null=True, verbose_name='C相功率因数')),
                ('sa', models.FloatField(blank=True, help_text='A相视在功率', null=True, verbose_name='A相视在功率')),
                ('sb', models.FloatField(blank=True, help_text='B相视在功率', null=True, verbose_name='B相视在功率')),
                ('sc', models.FloatField(blank=True, help_text='C相视在功率', null=True, verbose_name='C相视在功率')),
                ('t01', models.FloatField(blank=True, help_text='温度1', null=True, verbose_name='温度1')),
                ('t02', models.FloatField(blank=True, help_text='温度2', null=True, verbose_name='温度2')),
                ('t03', models.FloatField(blank=True, help_text='温度3', null=True, verbose_name='温度3')),
                ('t04', models.FloatField(blank=True, help_text='温度4', null=True, verbose_name='温度4')),
                ('t_alarm', models.IntegerField(blank=True, help_text='温度预警', null=True, verbose_name='温度预警')),
                ('t_protect', models.IntegerField(blank=True, help_text='温度告警', null=True, verbose_name='温度告警')),
                ('gl_alarm', models.IntegerField(blank=True, help_text='过流预警', null=True, verbose_name='过流预警')),
                ('gl_protect', models.IntegerField(blank=True, help_text='过流保护', null=True, verbose_name='过流保护')),
                ('qy_alarm', models.IntegerField(blank=True, help_text='欠压预警', null=True, verbose_name='欠压预警')),
                ('qy_protect', models.IntegerField(blank=True, help_text='欠压保护', null=True, verbose_name='欠压保护')),
                ('gy_alarm', models.IntegerField(blank=True, help_text='过压预警', null=True, verbose_name='过压预警')),
                ('gy_protect', models.IntegerField(blank=True, help_text='过压保护', null=True, verbose_name='过压保护')),
                ('ld_alarm', models.IntegerField(blank=True, help_text='漏电预警', null=True, verbose_name='漏电预警')),
                ('ld_protect', models.IntegerField(blank=True, help_text='漏电保护', null=True, verbose_name='漏电保护')),
                ('dl_alarm', models.IntegerField(blank=True, help_text='短路预警', null=True, verbose_name='短路预警')),
                ('dl_protect', models.IntegerField(blank=True, help_text='短路告警', null=True, verbose_name='短路告警')),
                ('device', models.OneToOneField(help_text='关联设备', on_delete=django.db.models.deletion.CASCADE, related_name='iot_breakers', to='equipments.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备模型-物联网断路器',
                'verbose_name_plural': '设备模型-物联网断路器',
            },
        ),
    ]
