# Generated by Django 4.2.16 on 2024-12-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0007_iotbreaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotbreaker',
            name='p',
            field=models.FloatField(blank=True, help_text='总有功功率', null=True, verbose_name='总有功功率'),
        ),
        migrations.AddField(
            model_name='iotbreaker',
            name='pf',
            field=models.FloatField(blank=True, help_text='总功率因数', null=True, verbose_name='总功率因数'),
        ),
    ]
