# Generated by Django 4.2.16 on 2024-12-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0008_iotbreaker_p_iotbreaker_pf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airconditioner',
            options={'verbose_name': '设备模型_空调设备', 'verbose_name_plural': '设备模型_空调设备'},
        ),
        migrations.AlterModelOptions(
            name='electricmeter',
            options={'verbose_name': '设备模型_电表', 'verbose_name_plural': '设备模型_电表'},
        ),
        migrations.AlterModelOptions(
            name='iotbreaker',
            options={'verbose_name': '设备模型_物联网断路器', 'verbose_name_plural': '设备模型_物联网断路器'},
        ),
        migrations.AlterModelOptions(
            name='personnelsensor',
            options={'verbose_name': '设备模型_人体存在感应传感器', 'verbose_name_plural': '设备模型_人体存在感应传感器'},
        ),
        migrations.AlterModelOptions(
            name='spacetightsensor',
            options={'verbose_name': '设备模型_门窗传感器', 'verbose_name_plural': '设备模型_门窗传感器'},
        ),
    ]
