# Generated by Django 4.2.16 on 2024-12-20 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0016_alter_categorymodemapping_device_type'),
        ('device_models', '0009_alter_airconditioner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airconditioner',
            options={'verbose_name': '设备模型-空调设备', 'verbose_name_plural': '设备模型-空调设备'},
        ),
        migrations.AlterModelOptions(
            name='iotbreaker',
            options={'verbose_name': '设备模型-物联网断路器', 'verbose_name_plural': '设备模型-物联网断路器'},
        ),
        migrations.AlterModelOptions(
            name='personnelsensor',
            options={'verbose_name': '设备模型-人体存在感应传感器', 'verbose_name_plural': '设备模型-人体存在感应传感器'},
        ),
        migrations.AlterModelOptions(
            name='electricmeter',
            options={'verbose_name': '设备模型-电表', 'verbose_name_plural': '设备模型-电表'},
        ),
        migrations.AlterModelOptions(
            name='spacetightsensor',
            options={'verbose_name': '设备模型-门窗传感器', 'verbose_name_plural': '设备模型-门窗传感器'},
        ),
        migrations.AlterField(
            model_name='electricmeter',
            name='epi',
            field=models.FloatField(blank=True, help_text='有功电能', null=True, verbose_name='有功电能'),
        ),
        migrations.CreateModel(
            name='PowerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('epi', models.FloatField(blank=True, help_text='有功电能', null=True, verbose_name='有功电能')),
                ('p', models.FloatField(blank=True, help_text='总有功功率', null=True, verbose_name='总有功功率')),
                ('device', models.OneToOneField(help_text='关联设备', on_delete=django.db.models.deletion.CASCADE, related_name='power_source', to='equipments.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备模型-电源',
                'verbose_name_plural': '设备模型-电源',
            },
        ),
        migrations.CreateModel(
            name='HiddenDangerMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('t01', models.FloatField(blank=True, help_text='温度1', null=True, verbose_name='温度1')),
                ('t02', models.FloatField(blank=True, help_text='温度2', null=True, verbose_name='温度2')),
                ('t03', models.FloatField(blank=True, help_text='温度3', null=True, verbose_name='温度3')),
                ('t04', models.FloatField(blank=True, help_text='温度4', null=True, verbose_name='温度4')),
                ('ma', models.FloatField(blank=True, help_text='漏电流', null=True, verbose_name='漏电流')),
                ('p', models.FloatField(blank=True, help_text='总有功功率', null=True, verbose_name='总有功功率')),
                ('device', models.OneToOneField(help_text='关联设备', on_delete=django.db.models.deletion.CASCADE, related_name='hidden_danger_monitor', to='equipments.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备模型-隐患监测',
                'verbose_name_plural': '设备模型-隐患监测',
            },
        ),
    ]
