# Generated by Django 4.2.16 on 2024-12-20 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0017_alter_categorymodemapping_device_type'),
        ('device_models', '0010_alter_airconditioner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorkedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('device', models.OneToOneField(help_text='关联设备', on_delete=django.db.models.deletion.CASCADE, related_name='net_worked_device', to='equipments.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备模型-联网设备',
                'verbose_name_plural': '设备模型-联网设备',
            },
        ),
    ]
