# Generated by Django 4.2.16 on 2024-12-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0011_networkeddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotbreaker',
            name='err_state',
            field=models.CharField(choices=[('normal', '正常'), ('warming', '预警'), ('alerting', '告警')], db_index=True, default='normal', help_text='断路器报警状态', verbose_name='断路器报警状态'),
        ),
    ]
