# Generated by Django 4.2.16 on 2024-12-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el_energy_signboards', '0002_alter_electricmeterload_options_delete_elnetworked'),
        ('device_models', '0012_iotbreaker_err_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetWorkedDevice',
        ),
    ]
