# Generated by Django 4.2.16 on 2024-12-25 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0021_alter_categorymodemapping_device_type'),
        ('device_models', '0013_delete_networkeddevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElMonitorInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('u0', models.FloatField(blank=True, help_text='零序电压', null=True, verbose_name='零序电压')),
                ('ua', models.FloatField(blank=True, help_text='A相电压', null=True, verbose_name='A相电压')),
                ('ub', models.FloatField(blank=True, help_text='B相电压', null=True, verbose_name='B相电压')),
                ('uc', models.FloatField(blank=True, help_text='C相电压', null=True, verbose_name='C相电压')),
                ('ia', models.FloatField(blank=True, help_text='A相电压', null=True, verbose_name='A相电压')),
                ('ib', models.FloatField(blank=True, help_text='B相电压', null=True, verbose_name='B相电压')),
                ('ic', models.FloatField(blank=True, help_text='C相电压', null=True, verbose_name='C相电压')),
                ('i0', models.FloatField(blank=True, help_text='零序电流', null=True, verbose_name='零序电流')),
                ('epi', models.FloatField(blank=True, help_text='正向有功总电能', null=True, verbose_name='正向有功总电能')),
                ('epe', models.FloatField(blank=True, help_text='反向有功总电能', null=True, verbose_name='反向有功总电能')),
                ('eql', models.FloatField(blank=True, help_text='正向无功总电能', null=True, verbose_name='正向无功总电能')),
                ('eqc', models.FloatField(blank=True, help_text='反向无功总电能', null=True, verbose_name='反向无功总电能')),
                ('p', models.FloatField(blank=True, help_text='总有功功率', null=True, verbose_name='总有功功率')),
                ('pa', models.FloatField(blank=True, help_text='A相有功功率', null=True, verbose_name='A相有功功率')),
                ('pb', models.FloatField(blank=True, help_text='B相有功功率', null=True, verbose_name='B相有功功率')),
                ('pc', models.FloatField(blank=True, help_text='C相有功功率', null=True, verbose_name='C相有功功率')),
                ('qa', models.FloatField(blank=True, help_text='A相无功功率', null=True, verbose_name='A相无功功率')),
                ('qb', models.FloatField(blank=True, help_text='B相无功功率', null=True, verbose_name='B相无功功率')),
                ('qc', models.FloatField(blank=True, help_text='C相无功功率', null=True, verbose_name='C相无功功率')),
                ('q', models.FloatField(blank=True, help_text='无功功率', null=True, verbose_name='无功功率')),
                ('pfa', models.FloatField(blank=True, help_text='A相功率因数', null=True, verbose_name='A相功率因数')),
                ('pfb', models.FloatField(blank=True, help_text='B相功率因数', null=True, verbose_name='B相功率因数')),
                ('pfc', models.FloatField(blank=True, help_text='C相功率因数', null=True, verbose_name='C相功率因数')),
                ('pf', models.FloatField(blank=True, help_text='总功率因数', null=True, verbose_name='总功率因数')),
                ('sa', models.FloatField(blank=True, help_text='A相视在功率', null=True, verbose_name='A相视在功率')),
                ('sb', models.FloatField(blank=True, help_text='B相视在功率', null=True, verbose_name='B相视在功率')),
                ('sc', models.FloatField(blank=True, help_text='C相视在功率', null=True, verbose_name='C相视在功率')),
                ('s', models.FloatField(blank=True, help_text='总视在功率', null=True, verbose_name='总视在功率')),
                ('device', models.OneToOneField(help_text='关联设备', on_delete=django.db.models.deletion.CASCADE, related_name='el_monitor_instrument', to='equipments.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备模型-电气监测仪表',
                'verbose_name_plural': '设备模型-电气监测仪表',
            },
        ),
    ]
