# Generated by Django 4.2.16 on 2024-12-26 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0022_alter_categorymodemapping_device_type'),
        ('device_models', '0014_elmonitorinstrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('ua', models.FloatField(blank=True, help_text='A相电压', null=True, verbose_name='A相电压')),
                ('ub', models.FloatField(blank=True, help_text='B相电压', null=True, verbose_name='B相电压')),
                ('uc', models.FloatField(blank=True, help_text='C相电压', null=True, verbose_name='C相电压')),
                ('uab', models.FloatField(blank=True, help_text='AB线电压', null=True, verbose_name='AB线电压')),
                ('ubc', models.FloatField(blank=True, help_text='BC线电压', null=True, verbose_name='BC线电压')),
                ('uca', models.FloatField(blank=True, help_text='CA线电压', null=True, verbose_name='CA线电压')),
                ('hz', models.FloatField(blank=True, help_text='频率', null=True, verbose_name='频率')),
                ('ia', models.FloatField(blank=True, help_text='A相电压', null=True, verbose_name='A相电压')),
                ('ib', models.FloatField(blank=True, help_text='B相电压', null=True, verbose_name='B相电压')),
                ('ic', models.FloatField(blank=True, help_text='C相电压', null=True, verbose_name='C相电压')),
                ('i0', models.FloatField(blank=True, help_text='零序电流', null=True, verbose_name='零序电流')),
                ('s', models.FloatField(blank=True, help_text='总视在功率', null=True, verbose_name='总视在功率')),
                ('sa', models.FloatField(blank=True, help_text='A相视在功率', null=True, verbose_name='A相视在功率')),
                ('sb', models.FloatField(blank=True, help_text='B相视在功率', null=True, verbose_name='B相视在功率')),
                ('sc', models.FloatField(blank=True, help_text='C相视在功率', null=True, verbose_name='C相视在功率')),
                ('p', models.FloatField(blank=True, help_text='总有功功率', null=True, verbose_name='总有功功率')),
                ('pa', models.FloatField(blank=True, help_text='A相有功功率', null=True, verbose_name='A相有功功率')),
                ('pb', models.FloatField(blank=True, help_text='B相有功功率', null=True, verbose_name='B相有功功率')),
                ('pc', models.FloatField(blank=True, help_text='C相有功功率', null=True, verbose_name='C相有功功率')),
                ('q', models.FloatField(blank=True, help_text='无功功率', null=True, verbose_name='无功功率')),
                ('qa', models.FloatField(blank=True, help_text='A相无功功率', null=True, verbose_name='A相无功功率')),
                ('qb', models.FloatField(blank=True, help_text='B相无功功率', null=True, verbose_name='B相无功功率')),
                ('qc', models.FloatField(blank=True, help_text='C相无功功率', null=True, verbose_name='C相无功功率')),
                ('pf', models.FloatField(blank=True, help_text='总功率因数', null=True, verbose_name='总功率因数')),
                ('pfa', models.FloatField(blank=True, help_text='A相功率因数', null=True, verbose_name='A相功率因数')),
                ('pfb', models.FloatField(blank=True, help_text='B相功率因数', null=True, verbose_name='B相功率因数')),
                ('pfc', models.FloatField(blank=True, help_text='C相功率因数', null=True, verbose_name='C相功率因数')),
                ('uunb', models.FloatField(blank=True, help_text='电压不平衡度', null=True, verbose_name='电压不平衡度')),
                ('iunb', models.FloatField(blank=True, help_text='电流不平衡度', null=True, verbose_name='电流不平衡度')),
                ('epi_demand', models.FloatField(blank=True, help_text='当前正向有功需量', null=True, verbose_name='当前正向有功需量')),
                ('epe_demand', models.FloatField(blank=True, help_text='当前反向有功需量', null=True, verbose_name='当前反向有功需量')),
                ('eql_demand', models.FloatField(blank=True, help_text='当前正向无功需量', null=True, verbose_name='当前正向无功需量')),
                ('eqc_demand', models.FloatField(blank=True, help_text='当前反向无功需量', null=True, verbose_name='当前反向无功需量')),
                ('epi', models.FloatField(blank=True, help_text='正向有功总电能', null=True, verbose_name='正向有功总电能')),
                ('thdu_ua', models.FloatField(blank=True, help_text='A相谐波电压总畸变率', null=True, verbose_name='A相谐波电压总畸变率')),
                ('thdu_ub', models.FloatField(blank=True, help_text='B相谐波电压总畸变率', null=True, verbose_name='B相谐波电压总畸变率')),
                ('thdu_uc', models.FloatField(blank=True, help_text='C相谐波电压总畸变率', null=True, verbose_name='C相谐波电压总畸变率')),
                ('thdu_ia', models.FloatField(blank=True, help_text='A相谐波电流总畸变率', null=True, verbose_name='A相谐波电流总畸变率')),
                ('thdu_ib', models.FloatField(blank=True, help_text='B相谐波电流总畸变率', null=True, verbose_name='B相谐波电流总畸变率')),
                ('thdu_ic', models.FloatField(blank=True, help_text='C相谐波电流总畸变率', null=True, verbose_name='C相谐波电流总畸变率')),
                ('device', models.OneToOneField(help_text='关联设备', on_delete=django.db.models.deletion.CASCADE, related_name='transformer', to='equipments.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备模型-变压器',
                'verbose_name_plural': '设备模型-变压器',
            },
        ),
        migrations.CreateModel(
            name='TfTemperatureMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('t01', models.FloatField(blank=True, help_text='温度1', null=True, verbose_name='温度1')),
                ('t02', models.FloatField(blank=True, help_text='温度2', null=True, verbose_name='温度2')),
                ('t03', models.FloatField(blank=True, help_text='温度3', null=True, verbose_name='温度3')),
                ('device', models.OneToOneField(help_text='关联设备', on_delete=django.db.models.deletion.CASCADE, related_name='tf_temperature_monitor', to='equipments.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备模型-变压器温度监测仪',
                'verbose_name_plural': '设备模型-变压器温度监测仪',
            },
        ),
    ]
