# Generated by Django 4.2.16 on 2024-12-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0015_transformer_tftemperaturemonitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformer',
            old_name='thdu_ia',
            new_name='thdi_ia',
        ),
        migrations.RenameField(
            model_name='transformer',
            old_name='thdu_ib',
            new_name='thdi_ib',
        ),
        migrations.RenameField(
            model_name='transformer',
            old_name='thdu_ic',
            new_name='thdi_ic',
        ),
    ]
