# Generated by Django 4.2.16 on 2025-01-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0016_rename_thdu_ia_transformer_thdi_ia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airconditioner',
            options={'verbose_name': '设备模型-中央空调监控', 'verbose_name_plural': '设备模型-中央空调监控'},
        ),
        migrations.AlterModelOptions(
            name='elmonitorinstrument',
            options={'verbose_name': '设备模型-三项电力仪表', 'verbose_name_plural': '设备模型-三项电力仪表'},
        ),
        migrations.AlterModelOptions(
            name='personnelsensor',
            options={'verbose_name': '设备模型-人体存在传感器', 'verbose_name_plural': '设备模型-人体存在传感器'},
        ),
        migrations.AlterModelOptions(
            name='powersource',
            options={'verbose_name': '设备模型-进线电源', 'verbose_name_plural': '设备模型-进线电源'},
        ),
        migrations.AlterModelOptions(
            name='tftemperaturemonitor',
            options={'verbose_name': '设备模型-变压器温度监测', 'verbose_name_plural': '设备模型-变压器温度监测'},
        ),
        migrations.AlterModelOptions(
            name='transformer',
            options={'verbose_name': '设备模型-变压器电力监测', 'verbose_name_plural': '设备模型-变压器电力监测'},
        ),
    ]
