# Generated by Django 4.2.16 on 2025-01-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0017_alter_airconditioner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotbreaker',
            name='ia',
            field=models.FloatField(blank=True, help_text='A相电流', null=True, verbose_name='A相电流'),
        ),
        migrations.AlterField(
            model_name='elmonitorinstrument',
            name='ia',
            field=models.FloatField(blank=True, help_text='A相电流', null=True, verbose_name='A相电流'),
        ),
        migrations.AlterField(
            model_name='elmonitorinstrument',
            name='ib',
            field=models.FloatField(blank=True, help_text='B相电流', null=True, verbose_name='B相电流'),
        ),
        migrations.AlterField(
            model_name='elmonitorinstrument',
            name='ic',
            field=models.FloatField(blank=True, help_text='C相电流', null=True, verbose_name='C相电流'),
        ),
        migrations.AlterField(
            model_name='iotbreaker',
            name='ib',
            field=models.FloatField(blank=True, help_text='B相电流', null=True, verbose_name='B相电流'),
        ),
        migrations.AlterField(
            model_name='iotbreaker',
            name='ic',
            field=models.FloatField(blank=True, help_text='C相电流', null=True, verbose_name='C相电流'),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='ia',
            field=models.FloatField(blank=True, help_text='A相电流', null=True, verbose_name='A相电流'),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='ib',
            field=models.FloatField(blank=True, help_text='B相电流', null=True, verbose_name='B相电流'),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='ic',
            field=models.FloatField(blank=True, help_text='C相电流', null=True, verbose_name='C相电流'),
        ),
    ]
