# Generated by Django 4.2.16 on 2025-01-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0018_iotbreaker_ia_alter_elmonitorinstrument_ia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotbreaker',
            name='lock',
            field=models.IntegerField(blank=True, help_text='挂锁控制', null=True, verbose_name='挂锁控制'),
        ),
    ]
