# Generated by Django 4.2.16 on 2025-02-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0019_alter_iotbreaker_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='elmonitorinstrument',
            name='hz',
            field=models.FloatField(blank=True, help_text='频率', null=True, verbose_name='频率'),
        ),
    ]
