# Generated by Django 4.2.16 on 2025-02-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0020_elmonitorinstrument_hz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iotbreaker',
            old_name='force_state',
            new_name='cmd_force_state',
        ),
        migrations.RenameField(
            model_name='iotbreaker',
            old_name='leakage_test',
            new_name='cmd_leakage_test',
        ),
        migrations.RenameField(
            model_name='iotbreaker',
            old_name='lock',
            new_name='cmd_lock',
        ),
        migrations.RenameField(
            model_name='iotbreaker',
            old_name='trip',
            new_name='cmd_trip',
        ),
        migrations.RemoveField(
            model_name='iotbreaker',
            name='dl_protect',
        ),
        migrations.RemoveField(
            model_name='iotbreaker',
            name='gl_protect',
        ),
        migrations.RemoveField(
            model_name='iotbreaker',
            name='gy_protect',
        ),
        migrations.RemoveField(
            model_name='iotbreaker',
            name='ld_protect',
        ),
        migrations.RemoveField(
            model_name='iotbreaker',
            name='qy_protect',
        ),
        migrations.RemoveField(
            model_name='iotbreaker',
            name='t_protect',
        ),
        migrations.AddField(
            model_name='iotbreaker',
            name='cmd_clr_bat',
            field=models.IntegerField(blank=True, help_text='电量清零', null=True, verbose_name='电量清零'),
        ),
        migrations.AddField(
            model_name='iotbreaker',
            name='cmd_switch',
            field=models.IntegerField(blank=True, help_text='断路器控制', null=True, verbose_name='断路器控制'),
        ),
        migrations.AddField(
            model_name='iotbreaker',
            name='dl_log',
            field=models.JSONField(blank=True, help_text='短路报警信息', null=True, verbose_name='短路报警信息'),
        ),
        migrations.AddField(
            model_name='iotbreaker',
            name='gl_log',
            field=models.JSONField(blank=True, help_text='过流报警信息', null=True, verbose_name='过流报警信息'),
        ),
        migrations.AddField(
            model_name='iotbreaker',
            name='gy_log',
            field=models.JSONField(blank=True, help_text='过压报警信息', null=True, verbose_name='过压报警信息'),
        ),
        migrations.AddField(
            model_name='iotbreaker',
            name='ld_log',
            field=models.JSONField(blank=True, help_text='漏电报警信息', null=True, verbose_name='漏电报警信息'),
        ),
        migrations.AddField(
            model_name='iotbreaker',
            name='qy_log',
            field=models.JSONField(blank=True, help_text='欠压报警信息', null=True, verbose_name='欠压报警信息'),
        ),
        migrations.AddField(
            model_name='iotbreaker',
            name='t_log',
            field=models.JSONField(blank=True, help_text='温度报警信息', null=True, verbose_name='温度报警信息'),
        ),
        migrations.AlterField(
            model_name='iotbreaker',
            name='dl_alarm',
            field=models.IntegerField(blank=True, help_text='短路报警状态', null=True, verbose_name='短路报警状态'),
        ),
        migrations.AlterField(
            model_name='iotbreaker',
            name='gl_alarm',
            field=models.IntegerField(blank=True, help_text='过流报警状态', null=True, verbose_name='过流报警状态'),
        ),
        migrations.AlterField(
            model_name='iotbreaker',
            name='gy_alarm',
            field=models.IntegerField(blank=True, help_text='过压报警状态', null=True, verbose_name='过压报警状态'),
        ),
        migrations.AlterField(
            model_name='iotbreaker',
            name='ld_alarm',
            field=models.IntegerField(blank=True, help_text='漏电报警状态', null=True, verbose_name='漏电报警状态'),
        ),
        migrations.AlterField(
            model_name='iotbreaker',
            name='qy_alarm',
            field=models.IntegerField(blank=True, help_text='欠压报警状态', null=True, verbose_name='欠压报警状态'),
        ),
        migrations.AlterField(
            model_name='iotbreaker',
            name='t_alarm',
            field=models.IntegerField(blank=True, help_text='温度报警状态', null=True, verbose_name='温度报警状态'),
        ),
    ]
