# Generated by Django 4.2.16 on 2025-02-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0021_rename_force_state_iotbreaker_cmd_force_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotbreaker',
            name='limit_p',
            field=models.FloatField(blank=True, help_text='限额功率', null=True, verbose_name='限额功率'),
        ),
    ]
