# Generated by Django 4.2.16 on 2025-02-25 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0033_alter_categorymodemapping_device_type'),
        ('device_models', '0022_iotbreaker_limit_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('state', models.IntegerField(blank=True, help_text='照明状态', null=True, verbose_name='照明状态')),
                ('switch', models.IntegerField(blank=True, help_text='照明控制', null=True, verbose_name='照明控制')),
                ('state01', models.IntegerField(blank=True, help_text='回路1状态', null=True, verbose_name='回路1状态')),
                ('switch01', models.IntegerField(blank=True, help_text='回路1控制', null=True, verbose_name='回路1控制')),
                ('brightness01', models.SmallIntegerField(blank=True, help_text='回路1亮度', null=True, verbose_name='回路1亮度')),
                ('state02', models.IntegerField(blank=True, help_text='回路2状态', null=True, verbose_name='回路2状态')),
                ('switch02', models.IntegerField(blank=True, help_text='回路2控制', null=True, verbose_name='回路2控制')),
                ('brightness02', models.SmallIntegerField(blank=True, help_text='回路2亮度', null=True, verbose_name='回路2亮度')),
                ('state03', models.IntegerField(blank=True, help_text='回路3状态', null=True, verbose_name='回路3状态')),
                ('switch03', models.IntegerField(blank=True, help_text='回路3控制', null=True, verbose_name='回路3控制')),
                ('brightness03', models.SmallIntegerField(blank=True, help_text='回路3亮度', null=True, verbose_name='回路3亮度')),
                ('state04', models.IntegerField(blank=True, help_text='回路4状态', null=True, verbose_name='回路4状态')),
                ('switch04', models.IntegerField(blank=True, help_text='回路4控制', null=True, verbose_name='回路4控制')),
                ('brightness04', models.SmallIntegerField(blank=True, help_text='回路4亮度', null=True, verbose_name='回路4亮度')),
                ('state05', models.IntegerField(blank=True, help_text='回路5状态', null=True, verbose_name='回路5状态')),
                ('switch05', models.IntegerField(blank=True, help_text='回路5控制', null=True, verbose_name='回路5控制')),
                ('brightness05', models.SmallIntegerField(blank=True, help_text='回路5亮度', null=True, verbose_name='回路5亮度')),
                ('state06', models.IntegerField(blank=True, help_text='回路6状态', null=True, verbose_name='回路6状态')),
                ('switch06', models.IntegerField(blank=True, help_text='回路6控制', null=True, verbose_name='回路6控制')),
                ('brightness06', models.SmallIntegerField(blank=True, help_text='回路6亮度', null=True, verbose_name='回路6亮度')),
                ('state07', models.IntegerField(blank=True, help_text='回路7状态', null=True, verbose_name='回路7状态')),
                ('switch07', models.IntegerField(blank=True, help_text='回路7控制', null=True, verbose_name='回路7控制')),
                ('brightness07', models.SmallIntegerField(blank=True, help_text='回路7亮度', null=True, verbose_name='回路7亮度')),
                ('state08', models.IntegerField(blank=True, help_text='回路8状态', null=True, verbose_name='回路8状态')),
                ('switch08', models.IntegerField(blank=True, help_text='回路8控制', null=True, verbose_name='回路8控制')),
                ('brightness08', models.SmallIntegerField(blank=True, help_text='回路8亮度', null=True, verbose_name='回路8亮度')),
                ('state09', models.IntegerField(blank=True, help_text='回路9状态', null=True, verbose_name='回路9状态')),
                ('switch09', models.IntegerField(blank=True, help_text='回路9控制', null=True, verbose_name='回路9控制')),
                ('brightness09', models.SmallIntegerField(blank=True, help_text='回路9亮度', null=True, verbose_name='回路9亮度')),
                ('state10', models.IntegerField(blank=True, help_text='回路10状态', null=True, verbose_name='回路10状态')),
                ('switch10', models.IntegerField(blank=True, help_text='回路10控制', null=True, verbose_name='回路10控制')),
                ('brightness10', models.SmallIntegerField(blank=True, help_text='回路10亮度', null=True, verbose_name='回路10亮度')),
                ('state11', models.IntegerField(blank=True, help_text='回路11状态', null=True, verbose_name='回路11状态')),
                ('switch11', models.IntegerField(blank=True, help_text='回路11控制', null=True, verbose_name='回路11控制')),
                ('brightness11', models.SmallIntegerField(blank=True, help_text='回路11亮度', null=True, verbose_name='回路11亮度')),
                ('state12', models.IntegerField(blank=True, help_text='回路12状态', null=True, verbose_name='回路12状态')),
                ('switch12', models.IntegerField(blank=True, help_text='回路12控制', null=True, verbose_name='回路12控制')),
                ('brightness12', models.SmallIntegerField(blank=True, help_text='回路12亮度', null=True, verbose_name='回路12亮度')),
                ('device', models.OneToOneField(help_text='关联设备', on_delete=django.db.models.deletion.CASCADE, related_name='light_monitor', to='equipments.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备模型-照明设备',
                'verbose_name_plural': '设备模型-照明设备',
            },
        ),
    ]
