# Generated by Django 4.2.16 on 2025-02-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0023_lightmonitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='brightness01',
            new_name='brightness1',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='brightness02',
            new_name='brightness2',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='brightness03',
            new_name='brightness3',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='brightness04',
            new_name='brightness4',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='brightness05',
            new_name='brightness5',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='brightness06',
            new_name='brightness6',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='brightness07',
            new_name='brightness7',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='brightness08',
            new_name='brightness8',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='brightness09',
            new_name='brightness9',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='state01',
            new_name='state1',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='state02',
            new_name='state2',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='state03',
            new_name='state3',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='state04',
            new_name='state4',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='state05',
            new_name='state5',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='state06',
            new_name='state6',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='state07',
            new_name='state7',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='state08',
            new_name='state8',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='state09',
            new_name='state9',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='switch01',
            new_name='switch1',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='switch02',
            new_name='switch2',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='switch03',
            new_name='switch3',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='switch04',
            new_name='switch4',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='switch05',
            new_name='switch5',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='switch06',
            new_name='switch6',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='switch07',
            new_name='switch7',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='switch08',
            new_name='switch8',
        ),
        migrations.RenameField(
            model_name='lightmonitor',
            old_name='switch09',
            new_name='switch9',
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='brightness13',
            field=models.SmallIntegerField(blank=True, help_text='回路13亮度', null=True, verbose_name='回路13亮度'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='brightness14',
            field=models.SmallIntegerField(blank=True, help_text='回路14亮度', null=True, verbose_name='回路14亮度'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='brightness15',
            field=models.SmallIntegerField(blank=True, help_text='回路15亮度', null=True, verbose_name='回路15亮度'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='brightness16',
            field=models.SmallIntegerField(blank=True, help_text='回路16亮度', null=True, verbose_name='回路16亮度'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='state13',
            field=models.IntegerField(blank=True, help_text='回路13状态', null=True, verbose_name='回路13状态'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='state14',
            field=models.IntegerField(blank=True, help_text='回路14状态', null=True, verbose_name='回路14状态'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='state15',
            field=models.IntegerField(blank=True, help_text='回路15状态', null=True, verbose_name='回路15状态'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='state16',
            field=models.IntegerField(blank=True, help_text='回路16状态', null=True, verbose_name='回路16状态'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='switch13',
            field=models.IntegerField(blank=True, help_text='回路13控制', null=True, verbose_name='回路13控制'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='switch14',
            field=models.IntegerField(blank=True, help_text='回路14控制', null=True, verbose_name='回路14控制'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='switch15',
            field=models.IntegerField(blank=True, help_text='回路15控制', null=True, verbose_name='回路15控制'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='switch16',
            field=models.IntegerField(blank=True, help_text='回路16控制', null=True, verbose_name='回路16控制'),
        ),
    ]
