# Generated by Django 4.2.16 on 2025-02-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0024_rename_brightness01_lightmonitor_brightness1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust',
            field=models.JSONField(blank=True, help_text='亮度调节', null=True, verbose_name='亮度调节'),
        ),
    ]
