# Generated by Django 4.2.16 on 2025-02-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0025_lightmonitor_adjust'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightmonitor',
            name='light_count',
            field=models.IntegerField(blank=True, help_text='当前亮灯数', null=True, verbose_name='当前亮灯数'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='total_count',
            field=models.IntegerField(blank=True, help_text='总回路数', null=True, verbose_name='总回路数'),
        ),
    ]
