# Generated by Django 4.2.16 on 2025-02-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0026_lightmonitor_light_count_lightmonitor_total_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotbreaker',
            name='switch',
        ),
    ]
