# Generated by Django 4.2.19 on 2025-03-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0027_remove_iotbreaker_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust1',
            field=models.SmallIntegerField(blank=True, help_text='回路1亮度调节', null=True, verbose_name='回路1亮度调节'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust10',
            field=models.SmallIntegerField(blank=True, help_text='回路10亮度调节', null=True, verbose_name='回路10亮度调节'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust11',
            field=models.SmallIntegerField(blank=True, help_text='回路11亮度调节', null=True, verbose_name='回路11亮度调节'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust12',
            field=models.SmallIntegerField(blank=True, help_text='回路12亮度调节', null=True, verbose_name='回路12亮度调节'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust13',
            field=models.SmallIntegerField(blank=True, help_text='回路13亮度调节', null=True, verbose_name='回路13亮度调节'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust14',
            field=models.SmallIntegerField(blank=True, help_text='回路14亮度调节', null=True, verbose_name='回路14亮度调节'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust15',
            field=models.SmallIntegerField(blank=True, help_text='回路15亮度调节', null=True, verbose_name='回路15亮度调节'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust16',
            field=models.SmallIntegerField(blank=True, help_text='回路16亮度调节', null=True, verbose_name='回路16亮度调节'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust2',
            field=models.SmallIntegerField(blank=True, help_text='回路2亮度调节', null=True, verbose_name='回路2亮度调节'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust3',
            field=models.SmallIntegerField(blank=True, help_text='回路3亮度调节', null=True, verbose_name='回路3亮度调节'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust4',
            field=models.SmallIntegerField(blank=True, help_text='回路4亮度调节', null=True, verbose_name='回路4亮度调节'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust5',
            field=models.SmallIntegerField(blank=True, help_text='回路5亮度调节', null=True, verbose_name='回路5亮度调节'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust6',
            field=models.SmallIntegerField(blank=True, help_text='回路6亮度调节', null=True, verbose_name='回路6亮度调节'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust7',
            field=models.SmallIntegerField(blank=True, help_text='回路7亮度调节', null=True, verbose_name='回路7亮度调节'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust8',
            field=models.SmallIntegerField(blank=True, help_text='回路8亮度调节', null=True, verbose_name='回路8亮度调节'),
        ),
        migrations.AddField(
            model_name='lightmonitor',
            name='adjust9',
            field=models.SmallIntegerField(blank=True, help_text='回路9亮度调节', null=True, verbose_name='回路9亮度调节'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='adjust',
            field=models.SmallIntegerField(blank=True, help_text='亮度一键调节', null=True, verbose_name='亮度一键调节'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='light_count',
            field=models.SmallIntegerField(blank=True, help_text='当前亮灯数', null=True, verbose_name='当前亮灯数'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state',
            field=models.SmallIntegerField(blank=True, help_text='照明状态', null=True, verbose_name='照明状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state1',
            field=models.SmallIntegerField(blank=True, help_text='回路1状态', null=True, verbose_name='回路1状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state10',
            field=models.SmallIntegerField(blank=True, help_text='回路10状态', null=True, verbose_name='回路10状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state11',
            field=models.SmallIntegerField(blank=True, help_text='回路11状态', null=True, verbose_name='回路11状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state12',
            field=models.SmallIntegerField(blank=True, help_text='回路12状态', null=True, verbose_name='回路12状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state13',
            field=models.SmallIntegerField(blank=True, help_text='回路13状态', null=True, verbose_name='回路13状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state14',
            field=models.SmallIntegerField(blank=True, help_text='回路14状态', null=True, verbose_name='回路14状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state15',
            field=models.SmallIntegerField(blank=True, help_text='回路15状态', null=True, verbose_name='回路15状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state16',
            field=models.SmallIntegerField(blank=True, help_text='回路16状态', null=True, verbose_name='回路16状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state2',
            field=models.SmallIntegerField(blank=True, help_text='回路2状态', null=True, verbose_name='回路2状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state3',
            field=models.SmallIntegerField(blank=True, help_text='回路3状态', null=True, verbose_name='回路3状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state4',
            field=models.SmallIntegerField(blank=True, help_text='回路4状态', null=True, verbose_name='回路4状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state5',
            field=models.SmallIntegerField(blank=True, help_text='回路5状态', null=True, verbose_name='回路5状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state6',
            field=models.SmallIntegerField(blank=True, help_text='回路6状态', null=True, verbose_name='回路6状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state7',
            field=models.SmallIntegerField(blank=True, help_text='回路7状态', null=True, verbose_name='回路7状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state8',
            field=models.SmallIntegerField(blank=True, help_text='回路8状态', null=True, verbose_name='回路8状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='state9',
            field=models.SmallIntegerField(blank=True, help_text='回路9状态', null=True, verbose_name='回路9状态'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch',
            field=models.SmallIntegerField(blank=True, help_text='照明一键开关', null=True, verbose_name='照明一键开关'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch1',
            field=models.SmallIntegerField(blank=True, help_text='回路1控制', null=True, verbose_name='回路1控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch10',
            field=models.SmallIntegerField(blank=True, help_text='回路10控制', null=True, verbose_name='回路10控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch11',
            field=models.SmallIntegerField(blank=True, help_text='回路11控制', null=True, verbose_name='回路11控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch12',
            field=models.SmallIntegerField(blank=True, help_text='回路12控制', null=True, verbose_name='回路12控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch13',
            field=models.SmallIntegerField(blank=True, help_text='回路13控制', null=True, verbose_name='回路13控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch14',
            field=models.SmallIntegerField(blank=True, help_text='回路14控制', null=True, verbose_name='回路14控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch15',
            field=models.SmallIntegerField(blank=True, help_text='回路15控制', null=True, verbose_name='回路15控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch16',
            field=models.SmallIntegerField(blank=True, help_text='回路16控制', null=True, verbose_name='回路16控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch2',
            field=models.SmallIntegerField(blank=True, help_text='回路2控制', null=True, verbose_name='回路2控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch3',
            field=models.SmallIntegerField(blank=True, help_text='回路3控制', null=True, verbose_name='回路3控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch4',
            field=models.SmallIntegerField(blank=True, help_text='回路4控制', null=True, verbose_name='回路4控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch5',
            field=models.SmallIntegerField(blank=True, help_text='回路5控制', null=True, verbose_name='回路5控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch6',
            field=models.SmallIntegerField(blank=True, help_text='回路6控制', null=True, verbose_name='回路6控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch7',
            field=models.SmallIntegerField(blank=True, help_text='回路7控制', null=True, verbose_name='回路7控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch8',
            field=models.SmallIntegerField(blank=True, help_text='回路8控制', null=True, verbose_name='回路8控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='switch9',
            field=models.SmallIntegerField(blank=True, help_text='回路9控制', null=True, verbose_name='回路9控制'),
        ),
        migrations.AlterField(
            model_name='lightmonitor',
            name='total_count',
            field=models.SmallIntegerField(blank=True, help_text='总回路数', null=True, verbose_name='总回路数'),
        ),
    ]
