# Generated by Django 4.2.20 on 2025-03-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0029_remove_lightmonitor_adjust_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotbreaker',
            name='state_sub',
            field=models.IntegerField(blank=True, help_text='断路器子状态', null=True, verbose_name='断路器子状态'),
        ),
        migrations.AlterField(
            model_name='iotbreaker',
            name='state',
            field=models.IntegerField(blank=True, help_text='断路器主状态', null=True, verbose_name='断路器主状态'),
        ),
    ]
