# Generated by Django 4.2.20 on 2025-03-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0030_iotbreaker_state_sub_alter_iotbreaker_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotbreaker',
            name='err_state',
        ),
    ]
