# Generated by Django 4.2.20 on 2025-04-01 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0036_alter_categorymodemapping_device_type'),
        ('device_models', '0031_remove_iotbreaker_err_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('on_count', models.SmallIntegerField(blank=True, help_text='当前闭合回路数', null=True, verbose_name='当前闭合回路数')),
                ('total_count', models.SmallIntegerField(blank=True, help_text='总回路数', null=True, verbose_name='总回路数')),
                ('state', models.SmallIntegerField(blank=True, help_text='回路状态', null=True, verbose_name='回路状态')),
                ('state1', models.SmallIntegerField(blank=True, help_text='回路1状态', null=True, verbose_name='回路1状态')),
                ('state2', models.SmallIntegerField(blank=True, help_text='回路2状态', null=True, verbose_name='回路2状态')),
                ('state3', models.SmallIntegerField(blank=True, help_text='回路3状态', null=True, verbose_name='回路3状态')),
                ('state4', models.SmallIntegerField(blank=True, help_text='回路4状态', null=True, verbose_name='回路4状态')),
                ('state5', models.SmallIntegerField(blank=True, help_text='回路5状态', null=True, verbose_name='回路5状态')),
                ('state6', models.SmallIntegerField(blank=True, help_text='回路6状态', null=True, verbose_name='回路6状态')),
                ('state7', models.SmallIntegerField(blank=True, help_text='回路7状态', null=True, verbose_name='回路7状态')),
                ('state8', models.SmallIntegerField(blank=True, help_text='回路8状态', null=True, verbose_name='回路8状态')),
                ('state9', models.SmallIntegerField(blank=True, help_text='回路9状态', null=True, verbose_name='回路9状态')),
                ('state10', models.SmallIntegerField(blank=True, help_text='回路10状态', null=True, verbose_name='回路10状态')),
                ('state11', models.SmallIntegerField(blank=True, help_text='回路11状态', null=True, verbose_name='回路11状态')),
                ('state12', models.SmallIntegerField(blank=True, help_text='回路12状态', null=True, verbose_name='回路12状态')),
                ('state13', models.SmallIntegerField(blank=True, help_text='回路13状态', null=True, verbose_name='回路13状态')),
                ('state14', models.SmallIntegerField(blank=True, help_text='回路14状态', null=True, verbose_name='回路14状态')),
                ('state15', models.SmallIntegerField(blank=True, help_text='回路15状态', null=True, verbose_name='回路15状态')),
                ('state16', models.SmallIntegerField(blank=True, help_text='回路16状态', null=True, verbose_name='回路16状态')),
                ('device', models.OneToOneField(help_text='关联设备', on_delete=django.db.models.deletion.CASCADE, related_name='switch_monitor', to='equipments.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备模型-开关监控设备',
                'verbose_name_plural': '设备模型-开关监控设备',
            },
        ),
    ]
