# Generated by Django 4.2.20 on 2025-04-02 18:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0037_alter_categorymodemapping_device_type'),
        ('device_models', '0032_switchmonitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('up_attr_data', models.JSONField(blank=True, help_text='属性最近一次上报值', null=True, verbose_name='属性最近一次上报值')),
                ('device', models.OneToOneField(help_text='关联设备', on_delete=django.db.models.deletion.CASCADE, related_name='environment_monitor', to='equipments.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备模型-环境系统设备',
                'verbose_name_plural': '设备模型-环境系统设备',
            },
        ),
    ]
