# Generated by Django 4.2.20 on 2025-07-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0033_environmentmonitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightmonitor',
            name='light_data',
            field=models.JSONField(blank=True, help_text='灯具上报数据: {"state1": 1, "brightness1": 100, ...}', null=True, verbose_name='灯具上报数据: {"state1": 1, "brightness1": 100, ...}'),
        ),
    ]
