# Generated by Django 4.2.20 on 2025-09-02 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0044_alter_categorymodemapping_device_type'),
        ('device_models', '0035_remove_lightmonitor_brightness1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaidElectricMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('epi', models.FloatField(blank=True, help_text='电表码值(度)', null=True, verbose_name='电表码值(度)')),
                ('state', models.SmallIntegerField(blank=True, help_text='开合状态', null=True, verbose_name='开合状态')),
                ('device', models.OneToOneField(help_text='关联设备', on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_electric_meter', to='equipments.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '设备模型-预付费电表',
                'verbose_name_plural': '设备模型-预付费电表',
            },
        ),
    ]
