# Generated by Django 4.2.20 on 2025-09-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0036_prepaidelectricmeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidelectricmeter',
            name='deep_valley_epi',
            field=models.FloatField(blank=True, help_text='深谷电能码值(度)', null=True, verbose_name='深谷电能码值(度)'),
        ),
        migrations.AddField(
            model_name='prepaidelectricmeter',
            name='flat_epi',
            field=models.FloatField(blank=True, help_text='平电能码值(度)', null=True, verbose_name='平电能码值(度)'),
        ),
        migrations.AddField(
            model_name='prepaidelectricmeter',
            name='on_peak_epi',
            field=models.FloatField(blank=True, help_text='峰电能码值(度)', null=True, verbose_name='峰电能码值(度)'),
        ),
        migrations.AddField(
            model_name='prepaidelectricmeter',
            name='top_epi',
            field=models.FloatField(blank=True, help_text='尖电能码值(度)', null=True, verbose_name='尖电能码值(度)'),
        ),
        migrations.AddField(
            model_name='prepaidelectricmeter',
            name='valley_epi',
            field=models.FloatField(blank=True, help_text='谷电能码值(度)', null=True, verbose_name='谷电能码值(度)'),
        ),
        migrations.AlterField(
            model_name='prepaidelectricmeter',
            name='epi',
            field=models.FloatField(blank=True, help_text='电表总码值(度)', null=True, verbose_name='电表总码值(度)'),
        ),
    ]
