# Generated by Django 4.2.20 on 2026-01-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_models', '0037_prepaidelectricmeter_deep_valley_epi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airconditioner',
            name='switch',
            field=models.CharField(blank=True, help_text='开关状态', max_length=10, null=True, verbose_name='开关状态'),
        ),
    ]
