# Generated by Django 4.2.16 on 2024-12-03 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("custom_servers", "0009_alter_domain_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wechat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wechatuser",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="服务域名",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="custom_servers.domain",
            ),
        ),
        migrations.AlterField(
            model_name="wechatuser",
            name="service_account_openid",
            field=models.CharField(
                default="", max_length=64, verbose_name="微信服务号openid"
            ),
        ),
        migrations.AlterField(
            model_name="wechatuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wechatuser",
            unique_together={("user", "domain")},
        ),
        migrations.CreateModel(
            name="WeappUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openid",
                    models.CharField(max_length=64, verbose_name="微信小程序openid"),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        default=None,
                        help_text="服务域名",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom_servers.domain",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "domain")},
            },
        ),
    ]
