# Generated by Django 4.2.16 on 2024-12-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wechat", "0002_wechatuser_domain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wechatuser",
            name="service_account_openid",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="微信服务号openid",
            ),
        ),
    ]
