# Generated by Django 5.1.7 on 2025-07-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_alter_wechatuser_service_account_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuser',
            name='unionid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='微信开放平台unionid'),
        ),
    ]
